<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 2;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Número C/C</b></th>';
			$tabela .= '<th align="center"><b>Processo Fundiário</b></th>';
			$tabela .= '<th align="center"><b>Opção de Benefício</b></th>';
			$tabela .= '<th align="center"><b>Nome do Produtor</b></th>';
			$tabela .= '<th align="center"><b>Local de Origem</b></th>';
			$tabela .= '<th align="center"><b>Local de Destino</b></th>';
			$tabela .= '<th align="center"><b>Município de Destino</b></th>';
			$tabela .= '<th align="center"><b>Setor de Atendimento</b></th>';
			$tabela .= '<th align="center"><b>Telefones</b></th>';
			$tabela .= '<th align="center"><b>Coord. UTM E</b></th>';
			$tabela .= '<th align="center"><b>Coord. UTM N</b></th>';
			$tabela .= '<th align="center"><b>Fuso da Coordenada UTM</b></th>';
			$tabela .= '<th align="center"><b>Família Residente?</b></th>';
			$tabela .= '<th align="center"><b>Técnico Responsável</b></th>';
			$tabela .= '<th align="center"><b>Lote</b></th>';
			$tabela .= '<th align="center"><b>Família Vulnerável?</b></th>';
			$tabela .= '<th align="center"><b>Família Indígena?</b></th>';
			$tabela .= '<th align="center"><b>Atendido pelo Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Motivo de Não Atendido pelo Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Observações de Não Atendido pelo Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrada - Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Data da Saída - Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>PEADS</b></th>';
			$tabela .= '<th align="center"><b>Atendido pelo Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Motivo de Não Atendido pelo Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Observações de Não Atendido pelo Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrada - Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Data da Saída - Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Tipo do Projeto 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Situação do Projeto 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Atendido como Ribeirinho</b></th>';
			$tabela .= '<th align="center"><b>Motivo de Não Atendido como Ribeirinho</b></th>';
			$tabela .= '<th align="center"><b>Observações de Não Atendido como Ribeirinho</b></th>';
			$tabela .= '<th align="center"><b>Pussuí CAR?</b></th>';
			$tabela .= '<th align="center"><b>Status do CAR</b></th>';
			$tabela .= '<th align="center"><b>Pussuí DAP?</b></th>';
			$tabela .= '<th align="center"><b>Status do DAP</b></th>';
			$tabela .= '<th align="center"><b>Pussuí DLA?</b></th>';
			$tabela .= '<th align="center"><b>Status do DLA</b></th>';
			$tabela .= '<th align="center"><b>Data da Aquisição do Imóvel</b></th>';
			$tabela .= '<th align="center"><b>Possuí Saldo Remanescente?</b></th>';
			$tabela .= '<th align="center"><b>Valor do Saldo</b></th>';
			$tabela .= '<th align="center"><b>Data da 1ª Parcela</b></th>';
			$tabela .= '<th align="center"><b>Data da 2ª Parcela</b></th>';
			$tabela .= '<th align="center"><b>Data da 3ª Parcela</b></th>';
			$tabela .= '<th align="center"><b>Data da Aplicação</b></th>';
			$tabela .= '<th align="center"><b>Status do Pagamento Remanescente</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("select * from VIEW_415421_GERAL order by FAMILIA_BENEFICIARIO asc", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FAMILIA_CODIGO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_NUMERO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_FUNDIARIO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_BENEFICIO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_BENEFICIARIO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_LOCALORIGEM'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_LOCALDESTINO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_MUNICIPIODESTINO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_SETORATEND_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_UTME'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_UTMN'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_FUSOGEO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_RESIDENTE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_TECNICO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_LOTERRC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_VULNERAVEL_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_INDIGENA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_ATEND421_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_MOTIVO421_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_OBS421'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DTENTRADA_421'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DTSAIDA_421'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_PEADS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_ATEND415_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_MOTIVO415_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_OBS415'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DTENTRADA_415'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DTSAIDA_415'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_TPPROJ415_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_SITPROJ415_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_ATENDRIR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_MOTIVORIR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_OBSRIR'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_CAR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_CAR_STATUS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DAP_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DAP_STATUS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DLA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['DADOS_DLA_STATUS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_DATAAQUISICAO'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_POSSUISALDO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_VALOR'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_DTPARC_01'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_DTPARC_02'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_DTPARC_03'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_DATAPLAPLIC'].'</td>';
				$tabela .= '<td>'.$vetor['SALDO_STATUS_DESC'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_familias.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>