<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 2;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Número C/C</b></th>';
			$tabela .= '<th align="center"><b>Opção de Benefício</b></th>';
			$tabela .= '<th align="center"><b>Nome do Produtor</b></th>';
			$tabela .= '<th align="center"><b>Local de Destino</b></th>';
			$tabela .= '<th align="center"><b>Município de Destino</b></th>';
			$tabela .= '<th align="center"><b>Técnico Responsável</b></th>';
			$tabela .= '<th align="center"><b>Atendido pelo Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrada - Proj. 4.2.1</b></th>';
			$tabela .= '<th align="center"><b>Atendido pelo Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrada - Proj. 4.1.5</b></th>';
			$tabela .= '<th align="center"><b>Reside no Lote?</b></th>';
			$tabela .= '<th align="center"><b>Produz no Lote?</b></th>';
			$tabela .= '<th align="center"><b>De que forma situações ocorridas no decorrer do processo de remanejamento, como: prazos, caracteríticas da propriedade etc, interferiram na recepção da ATES e no desenvolvimento do lote?</b></th>';
			$tabela .= '<th align="center"><b>Quais os fatores objetivos e, de que forma esses fatores influenciaram de forma negativa na renda bruta anual?</b></th>';
			$tabela .= '<th align="center"><b>% da Renda proveniente do Lote</b></th>';
			$tabela .= '<th align="center"><b>% da Renda não proveniente ao Lote</b></th>';
			$tabela .= '<th align="center"><b>Faixa de Renda Bruta Anual (R$) (Para fins de Crédito Rural/EMATER)</b></th>';
			$tabela .= '<th align="center"><b>Faixa de Renda Bruta Anual (R$) (Cálculo de Faixas/Equilíbrio)</b></th>';
			$tabela .= '<th align="center"><b>Valor da Renda Bruta Anual (R$)</b></th>';
			$tabela .= '<th align="center"><b>Acesso a Benefícios de Transferência de Renda?</b></th>';
			$tabela .= '<th align="center"><b>Valor dos Benefícios de Transferência de Renda (ANUAL)(R$)</b></th>';
			$tabela .= '<th align="center"><b>Acesso a Benefícios Sociais Socioassistênciais?</b></th>';
			$tabela .= '<th align="center"><b>Valor dos Benefícios Sociais Socioassistênciais (ANUAL)(R$)</b></th>';
			$tabela .= '<th align="center"><b>Alguém Possuí Emprego Fixo Fora do Lote?</b></th>';
			$tabela .= '<th align="center"><b>Valor Total dos Rendimentos de Empregos Fixos Fora do Lote (ANUAL)(R$)</b></th>';
			$tabela .= '<th align="center"><b>Alguém Possuí Emprego Temporário Fora do Lote?</b></th>';
			$tabela .= '<th align="center"><b>Valor Total dos Rendimentos de Empregos Temporários Fora do Lote (ANUAL)(R$)</b></th>';
			$tabela .= '<th align="center"><b>Alguém Possuí Renda com Pesca Comercial?</b></th>';
			$tabela .= '<th align="center"><b>Valor Total da Renda da Pesca Comercial (ANUAL)(R$)</b></th>';
			$tabela .= '<th align="center"><b>Número de Membros da Família</b></th>';
			$tabela .= '<th align="center"><b>Força de Trabalho Familiar</b></th>';
			$tabela .= '<th align="center"><b>Valor do Cálculo da Força de Trabalho Familiar</b></th>';
			$tabela .= '<th align="center"><b>Família Atendida Como Vulnerário pelo Projeto 4.6.2?</b></th>';
			$tabela .= '<th align="center"><b>Faixa de Renda Per Capta</b></th>';
			$tabela .= '<th align="center"><b>Valor Calculado da Renda Per Capta (R$)</b></th>';
			$tabela .= '<th align="center"><b>Faixa de Vulnerabilidade, Conforme IDF (2017)</b></th>';
			$tabela .= '<th align="center"><b>Valor Calculado do IDF da Família em 2017 (ou Último)</b></th>';
			$tabela .= '<th align="center"><b>Mostra interesse em desenvolver o lote sob o ponto de vista produtivo?</b></th>';
			$tabela .= '<th align="center"><b>É receptivo às ações da ATES?</b></th>';
			$tabela .= '<th align="center"><b>Participa das atividades coletivas e socioculturais promovidas pelo Projeto de Reparação?</b></th>';
			$tabela .= '<th align="center"><b>Acesso ou Distância dificultam seguir as orientações de ATES?</b></th>';
			$tabela .= '<th align="center"><b>Recursos financeiros dificultam seguir as orientações de ATES?</b></th>';
			$tabela .= '<th align="center"><b>Mão de Obra disponpivel dificulta seguir as orientações de ATES?</b></th>';
			$tabela .= '<th align="center"><b>Resistência-Melindres dificultam seguir as orientações de ATES?</b></th>';
			$tabela .= '<th align="center"><b>Existem atividades planejadas para o futuro?</b></th>';
			$tabela .= '<th align="center"><b>Possui CAR?</b></th>';
			$tabela .= '<th align="center"><b>Possui DAP?</b></th>';
			$tabela .= '<th align="center"><b>Possui DLA?</b></th>';
			$tabela .= '<th align="center"><b>Tipo de Moradia</b></th>';
			$tabela .= '<th align="center"><b>Tipo de Acesso à Energia Elétrica</b></th>';
			$tabela .= '<th align="center"><b>Tipo de Acesso à Água</b></th>';
			$tabela .= '<th align="center"><b>Principal Meio de Transporte/Veículo</b></th>';
			$tabela .= '<th align="center"><b>Possui máquinas e implementos agrícolas?</b></th>';
			$tabela .= '<th align="center"><b>Possui ferramentas motorizadas?</b></th>';
			$tabela .= '<th align="center"><b>Possui galinheiro?</b></th>';
			$tabela .= '<th align="center"><b>Possui aprisco (curral para ovelhas)?</b></th>';
			$tabela .= '<th align="center"><b>Possui chiqueiro de porco?</b></th>';
			$tabela .= '<th align="center"><b>Possui curral para gado?</b></th>';
			$tabela .= '<th align="center"><b>Possui cocho para gado?</b></th>';
			$tabela .= '<th align="center"><b>Possui barcaça para secagem de cacau?</b></th>';
			$tabela .= '<th align="center"><b>Possui viveiro de mudas?</b></th>';
			$tabela .= '<th align="center"><b>Área Total da Propriedade (hectares)</b></th>';
			$tabela .= '<th align="center"><b>Faixa da Área Total da Propriedade</b></th>';
			$tabela .= '<th align="center"><b>Área de Floresta (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Floresta</b></th>';
			$tabela .= '<th align="center"><b>Área de Capoeira (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Capoeira</b></th>';
			$tabela .= '<th align="center"><b>Área de Pasto Sujo (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Pasto Sujo</b></th>';
			$tabela .= '<th align="center"><b>Área de Pasto Limpo (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Pasto Limpo</b></th>';
			$tabela .= '<th align="center"><b>Área de Cacau Produtivo (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Cacau Produtivo</b></th>';
			$tabela .= '<th align="center"><b>Área de Cacau Não Produtivo (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Cacau Não Produtivo</b></th>';
			$tabela .= '<th align="center"><b>Área de Outras Culturas Perenes (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Outras Culturas Perenes</b></th>';
			$tabela .= '<th align="center"><b>Área de Lavouras Temporárias (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Lavouras Temporárias</b></th>';
			$tabela .= '<th align="center"><b>Área de Pomar/Quintal Agroflorestal (hectares)</b></th>';
			$tabela .= '<th align="center"><b>% Relativa de Pomar/Quintal Agroflorestal</b></th>';
			$tabela .= '<th align="center"><b>Bovinocultura de Cria (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Bovinocultura de Cria (Número de Cabeças)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Aves (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Aves (Número de Cabeças)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Suínos (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Suínos (Número de Cabeças)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Caprinos e Ovinos (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Criação de Caprinos e Ovinos (Número de Cabeças)</b></th>';
			$tabela .= '<th align="center"><b>Piscicultura m² de Lamina de Água (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Piscicultura m² de Lamina de Água (Qtde.)</b></th>';
			$tabela .= '<th align="center"><b>Lavoura de Cacau (Número de Pés) (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Lavoura de Cacau (Número de Pés)</b></th>';
			$tabela .= '<th align="center"><b>Produtividade da Lavoura de Cacau (Kg/Pé) (Faixa)</b></th>';
			$tabela .= '<th align="center"><b>Produtividade da Lavoura de Cacau (Kg/Pé)</b></th>';
			$tabela .= '<th align="center"><b>Possui Lavouras Perenes?</b></th>';
			$tabela .= '<th align="center"><b>Possui Lavouras Semi-Perenes?</b></th>';
			$tabela .= '<th align="center"><b>Possui Lavouras Temporárias? (Grãos e Tubérculos)</b></th>';
			$tabela .= '<th align="center"><b>Possui Lavouras de Hortaliças?</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_415421_FAMILIAS.FAMILIA_CODIGO, TAB_415421_FAMILIAS.FAMILIA_NUMERO, TAB_APOIO_BENEFICIOS.DESCRICAO AS FAMILIA_BENEFICIO_DESC, TAB_415421_FAMILIAS.FAMILIA_BENEFICIARIO, TAB_415421_FAMILIAS.FAMILIA_LOCALDESTINO, TAB_APOIO_MUNICIPIOS.DESCRICAO AS FAMILIA_MUNICIPIODESTINO_DESC, TAB_APOIO_TECNICOS.DESCRICAO AS FAMILIA_TECNICO_DESC, TAB_APOIO_TPATENDIMENTO_421.DESCRICAO AS FAMILIA_ATEND421_TIPO, TAB_APOIO_TPATENDIMENTO_415.DESCRICAO AS FAMILIA_ATEND415_TIPO, TAB_415421_DADOSGERAIS.DADOS_DTENTRADA_421 AS FAMILIA_DATAENTRADA421_TIPO, TAB_415421_DADOSGERAIS.DADOS_DTENTRADA_415 AS FAMILIA_DATAENTRADA415_TIPO, TAB_415421_EMATER.EMATER_G01_Q01, TAB_415421_EMATER.EMATER_G01_Q02, TAB_415421_EMATER.EMATER_G02_Q01, TAB_415421_EMATER.EMATER_G02_Q02, TAB_415421_EMATER.EMATER_G03_Q01,  TAB_415421_EMATER.EMATER_G03_Q02, TAB_415421_EMATER.EMATER_G03_Q03, TAB_415421_EMATER.EMATER_G03_Q03A, TAB_415421_EMATER.EMATER_G03_Q04, TAB_415421_EMATER.EMATER_G04_Q01, TAB_415421_EMATER.EMATER_G04_Q02, TAB_415421_EMATER.EMATER_G04_Q03, TAB_415421_EMATER.EMATER_G04_Q04, TAB_415421_EMATER.EMATER_G04_Q05, TAB_415421_EMATER.EMATER_G04_Q06, TAB_415421_EMATER.EMATER_G04_Q07, TAB_415421_EMATER.EMATER_G04_Q08, TAB_415421_EMATER.EMATER_G04_Q09, TAB_415421_EMATER.EMATER_G04_Q10, TAB_415421_EMATER.EMATER_G05_Q01, TAB_415421_EMATER.EMATER_G05_Q02, TAB_415421_EMATER.EMATER_G05_Q03, TAB_415421_EMATER.EMATER_G05_Q04, TAB_415421_EMATER.EMATER_G05_Q05, TAB_415421_EMATER.EMATER_G05_Q06, TAB_415421_EMATER.EMATER_G05_Q07, TAB_415421_EMATER.EMATER_G05_Q08, TAB_415421_EMATER.EMATER_G06_Q01, TAB_415421_EMATER.EMATER_G06_Q02, TAB_415421_EMATER.EMATER_G06_Q03, TAB_415421_EMATER.EMATER_G06_Q04, TAB_415421_EMATER.EMATER_G06_Q05, TAB_415421_EMATER.EMATER_G06_Q06, TAB_415421_EMATER.EMATER_G06_Q07, TAB_415421_EMATER.EMATER_G06_Q08, TAB_415421_EMATER.EMATER_G06_Q09, TAB_415421_EMATER.EMATER_G06_Q10, TAB_415421_EMATER.EMATER_G06_Q11, TAB_415421_EMATER.EMATER_G07_Q01, TAB_415421_EMATER.EMATER_G07_Q02, TAB_415421_EMATER.EMATER_G07_Q03, TAB_415421_EMATER.EMATER_G07_Q04, TAB_415421_EMATER.EMATER_G07_Q05, TAB_415421_EMATER.EMATER_G07_Q06, TAB_415421_EMATER.EMATER_G07_Q07, TAB_415421_EMATER.EMATER_G07_Q08, TAB_415421_EMATER.EMATER_G07_Q09, TAB_415421_EMATER.EMATER_G07_Q10, TAB_415421_EMATER.EMATER_G07_Q11, TAB_415421_EMATER.EMATER_G07_Q12, TAB_415421_EMATER.EMATER_G07_Q13, TAB_415421_EMATER.EMATER_G08_Q01, TAB_415421_EMATER.EMATER_G08_Q02, TAB_415421_EMATER.EMATER_G08_Q03, TAB_415421_EMATER.EMATER_G08_Q04, TAB_415421_EMATER.EMATER_G08_Q05, TAB_415421_EMATER.EMATER_G08_Q06, TAB_415421_EMATER.EMATER_G08_Q07, TAB_415421_EMATER.EMATER_G08_Q08, TAB_415421_EMATER.EMATER_G08_Q09, TAB_415421_EMATER.EMATER_G08_Q10, TAB_415421_EMATER.EMATER_G08_Q11, TAB_415421_EMATER.EMATER_G08_Q12, TAB_415421_EMATER.EMATER_G08_Q13, TAB_415421_EMATER.EMATER_G08_Q14, TAB_415421_EMATER.EMATER_G08_Q15, TAB_415421_EMATER.EMATER_G08_Q16, TAB_415421_EMATER.EMATER_G08_Q17, TAB_415421_EMATER.EMATER_G08_Q18, TAB_415421_EMATER.EMATER_G08_Q19, TAB_415421_EMATER.EMATER_G08_Q20, TAB_415421_EMATER.EMATER_G09_Q01, TAB_415421_EMATER.EMATER_G09_Q02, TAB_415421_EMATER.EMATER_G09_Q03, TAB_415421_EMATER.EMATER_G09_Q04, TAB_415421_EMATER.EMATER_G09_Q05, TAB_415421_EMATER.EMATER_G09_Q06, TAB_415421_EMATER.EMATER_G09_Q07, TAB_415421_EMATER.EMATER_G09_Q08, TAB_415421_EMATER.EMATER_G09_Q09, TAB_415421_EMATER.EMATER_G09_Q10, TAB_415421_EMATER.EMATER_G09_Q11, TAB_415421_EMATER.EMATER_G09_Q12, TAB_415421_EMATER.EMATER_G09_Q13, TAB_415421_EMATER.EMATER_G09_Q14, TAB_415421_EMATER.EMATER_G09_Q15, TAB_415421_EMATER.EMATER_G09_Q16, TAB_415421_EMATER.EMATER_G09_Q17, TAB_415421_EMATER.EMATER_G09_Q18, TAB_415421_EMATER.EMATER_G09_Q19, TAB_415421_EMATER.EMATER_G09_Q20 FROM TAB_415421_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BENEFICIOS ON TAB_415421_FAMILIAS.FAMILIA_BENEFICIO = TAB_APOIO_BENEFICIOS.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS ON TAB_415421_FAMILIAS.FAMILIA_MUNICIPIODESTINO = TAB_APOIO_MUNICIPIOS.ID LEFT OUTER JOIN TAB_APOIO_TECNICOS ON TAB_415421_FAMILIAS.FAMILIA_TECNICO = TAB_APOIO_TECNICOS.ID LEFT OUTER JOIN TAB_415421_DADOSGERAIS ON TAB_415421_DADOSGERAIS.FAMILIA_CODIGO = TAB_415421_FAMILIAS.FAMILIA_CODIGO LEFT OUTER JOIN TAB_APOIO_TPATENDIMENTO AS TAB_APOIO_TPATENDIMENTO_421 ON TAB_415421_DADOSGERAIS.DADOS_ATEND421 = TAB_APOIO_TPATENDIMENTO_421.ID LEFT OUTER JOIN TAB_APOIO_TPATENDIMENTO AS TAB_APOIO_TPATENDIMENTO_415 ON TAB_415421_DADOSGERAIS.DADOS_ATEND415 = TAB_APOIO_TPATENDIMENTO_415.ID LEFT OUTER JOIN TAB_415421_EMATER ON TAB_415421_EMATER.FAMILIA_CODIGO = TAB_415421_FAMILIAS.FAMILIA_CODIGO WHERE TAB_415421_EMATER.EMATER_ID IS NOT NULL;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FAMILIA_CODIGO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_NUMERO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_BENEFICIO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_BENEFICIARIO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_LOCALDESTINO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_MUNICIPIODESTINO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_TECNICO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ATEND421_TIPO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DATAENTRADA421_TIPO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ATEND415_TIPO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DATAENTRADA415_TIPO'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G01_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G01_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G02_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G02_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G03_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G03_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G03_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G03_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q09'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G04_Q10'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G05_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q11'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q09'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G06_Q10'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q09'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q10'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q11'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q12'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G07_Q13'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q03'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q04'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q09'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q10'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q11'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q12'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q13'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q14'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q15'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q16'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q17'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q18'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q19'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G08_Q20'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q01'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q02'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q05'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q06'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q07'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q08'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q09'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q10'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q11'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q12'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q13'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q14'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q15'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q16'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q17'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q18'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q19'].'</td>';
				$tabela .= '<td>'.$vetor['EMATER_G09_Q20'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_emater.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>