<?php 
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 8;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			function reverse_date( $date ){
				return ( strstr( $date, '-' ) ) ? implode( '/', array_reverse( explode( '-', $date ) ) ) : implode( '-', array_reverse( explode(                '/', $date ) )      );
			}
			$idEntrega = $_GET['idEntrega'];
			$idAldeia = $_GET['idAldeia'];

			$INDIG_MOVENT_DATA = reverse_date($_POST['INDIG_MOVENT_DATA']);
			$INDIG_MOVENT_TECNICO = $_POST['INDIG_MOVENT_TECNICO'];
			$INDIG_MOVENT_PESCA_CX120 = $_POST['INDIG_MOVENT_PESCA_CX120'];
			$INDIG_MOVENT_PESCA_CX160 = $_POST['INDIG_MOVENT_PESCA_CX160'];
			$INDIG_MOVENT_PESCA_GELO = $_POST['INDIG_MOVENT_PESCA_GELO'];
			$INDIG_MOVENT_PESCA_GL20 = $_POST['INDIG_MOVENT_PESCA_GL20'];
			$INDIG_MOVENT_PESCA_GL50 = $_POST['INDIG_MOVENT_PESCA_GL50'];
			$INDIG_MOVENT_PESCA_COMB = $_POST['INDIG_MOVENT_PESCA_COMB'];
			$INDIG_MOVENT_TRANS_CX120 = $_POST['INDIG_MOVENT_TRANS_CX120'];
			$INDIG_MOVENT_TRANS_CX160 = $_POST['INDIG_MOVENT_TRANS_CX160'];
			$INDIG_MOVENT_TRANS_GELO = $_POST['INDIG_MOVENT_TRANS_GELO'];
			$INDIG_MOVENT_TRANS_GL20 = $_POST['INDIG_MOVENT_TRANS_GL20'];
			$INDIG_MOVENT_TRANS_GL50 = $_POST['INDIG_MOVENT_TRANS_GL50'];
			$INDIG_MOVENT_TRANS_COMB = $_POST['INDIG_MOVENT_TRANS_COMB'];
			$INDIG_MOVENT_CONSERV_GELO = $_POST['INDIG_MOVENT_CONSERV_GELO'];
			$INDIG_MOVENT_RANCHO_GELO = $_POST['INDIG_MOVENT_RANCHO_GELO'];
			$INDIG_MOVENT_PESCA_CX120_DEV = $_POST['INDIG_MOVENT_PESCA_CX120_DEV'];
			$INDIG_MOVENT_PESCA_CX120_CHECK = '2';
			$INDIG_MOVENT_PESCA_CX160_DEV = $_POST['INDIG_MOVENT_PESCA_CX160_DEV'];
			$INDIG_MOVENT_PESCA_CX160_CHECK = '2';
			$INDIG_MOVENT_PESCA_GL20_DEV = $_POST['INDIG_MOVENT_PESCA_GL20_DEV'];
			$INDIG_MOVENT_PESCA_GL20_CHECK = '2';
			$INDIG_MOVENT_PESCA_GL50_DEV = $_POST['INDIG_MOVENT_PESCA_GL50_DEV'];
			$INDIG_MOVENT_PESCA_GL50_CHECK = '2';
			$INDIG_MOVENT_TRANS_CX120_DEV = $_POST['INDIG_MOVENT_TRANS_CX120_DEV'];
			$INDIG_MOVENT_TRANS_CX120_CHECK = '2';
			$INDIG_MOVENT_TRANS_CX160_DEV = $_POST['INDIG_MOVENT_TRANS_CX160_DEV'];
			$INDIG_MOVENT_TRANS_CX160_CHECK = '2';
			$INDIG_MOVENT_TRANS_GL20_DEV = $_POST['INDIG_MOVENT_TRANS_GL20_DEV'];
			$INDIG_MOVENT_TRANS_GL20_CHECK = '2';
			$INDIG_MOVENT_TRANS_GL50_DEV = $_POST['INDIG_MOVENT_TRANS_GL50_DEV'];
			$INDIG_MOVENT_TRANS_GL50_CHECK = '2';
//			$INDIG_MOVENT_DOCUMENTO = $_POST['INDIG_MOVENT_DOCUMENTO'];

		
			$sql = mysql_query("UPDATE TAB_INDIG_PROD_ENTREGAS SET INDIG_MOVENT_DATA = '$INDIG_MOVENT_DATA', INDIG_MOVENT_TECNICO = '$INDIG_MOVENT_TECNICO', INDIG_MOVENT_PESCA_CX120 = '$INDIG_MOVENT_PESCA_CX120', INDIG_MOVENT_PESCA_CX160 = '$INDIG_MOVENT_PESCA_CX160', INDIG_MOVENT_PESCA_GELO = '$INDIG_MOVENT_PESCA_GELO', INDIG_MOVENT_PESCA_GL20 = '$INDIG_MOVENT_PESCA_GL20', INDIG_MOVENT_PESCA_GL50 = '$INDIG_MOVENT_PESCA_GL50', INDIG_MOVENT_PESCA_COMB = '$INDIG_MOVENT_PESCA_COMB', INDIG_MOVENT_TRANS_CX120 = '$INDIG_MOVENT_TRANS_CX120', INDIG_MOVENT_TRANS_CX160 = '$INDIG_MOVENT_TRANS_CX160', INDIG_MOVENT_TRANS_GELO = '$INDIG_MOVENT_TRANS_GELO', INDIG_MOVENT_TRANS_GL20 = '$INDIG_MOVENT_TRANS_GL20', INDIG_MOVENT_TRANS_GL50 = '$INDIG_MOVENT_TRANS_GL50', INDIG_MOVENT_TRANS_COMB = '$INDIG_MOVENT_TRANS_COMB', INDIG_MOVENT_CONSERV_GELO = '$INDIG_MOVENT_CONSERV_GELO', INDIG_MOVENT_RANCHO_GELO = '$INDIG_MOVENT_RANCHO_GELO', INDIG_MOVENT_PESCA_CX120_DEV = '$INDIG_MOVENT_PESCA_CX120_DEV', INDIG_MOVENT_PESCA_CX120_CHECK = '$INDIG_MOVENT_PESCA_CX120_CHECK', INDIG_MOVENT_PESCA_CX160_DEV = '$INDIG_MOVENT_PESCA_CX160_DEV', INDIG_MOVENT_PESCA_CX160_CHECK = '$INDIG_MOVENT_PESCA_CX160_CHECK', INDIG_MOVENT_PESCA_GL20_DEV = '$INDIG_MOVENT_PESCA_GL20_DEV', INDIG_MOVENT_PESCA_GL20_CHECK = '$INDIG_MOVENT_PESCA_GL20_CHECK', INDIG_MOVENT_PESCA_GL50_DEV = '$INDIG_MOVENT_PESCA_GL50_DEV', INDIG_MOVENT_PESCA_GL50_CHECK = '$INDIG_MOVENT_PESCA_GL50_CHECK', INDIG_MOVENT_TRANS_CX120_DEV = '$INDIG_MOVENT_TRANS_CX120_DEV', INDIG_MOVENT_TRANS_CX120_CHECK = '$INDIG_MOVENT_TRANS_CX120_CHECK', INDIG_MOVENT_TRANS_CX160_DEV = '$INDIG_MOVENT_TRANS_CX160_DEV', INDIG_MOVENT_TRANS_CX160_CHECK = '$INDIG_MOVENT_TRANS_CX160_CHECK', INDIG_MOVENT_TRANS_GL20_DEV = '$INDIG_MOVENT_TRANS_GL20_DEV', INDIG_MOVENT_TRANS_GL20_CHECK = '$INDIG_MOVENT_TRANS_GL20_CHECK', INDIG_MOVENT_TRANS_GL50_DEV = '$INDIG_MOVENT_TRANS_GL50_DEV', INDIG_MOVENT_TRANS_GL50_CHECK = '$INDIG_MOVENT_TRANS_GL50_CHECK' WHERE INDIG_MOVENT_ID = '$idEntrega' AND INDIG_MOVENT_ALDEIA = '$idAldeia';", $db) or die(mysql_error());
		/*
			echo"<script language=\"JavaScript\">
				alert('Inserido com sucesso!');
				</script>";
		*/				
			echo"<script language=\"JavaScript\">
				location.href=\"cadastrar_indig_dados_prod_entregas.php?idEntrega=$idEntrega&idAldeia=$idAldeia\";
				</script>";
		}
	}
?>
<?php require_once("includes/header-recebe.php");?>