<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Status do Acompanhamento</b></th>';
			$tabela .= '<th align="center"><b>Número Questionário</b></th>';
			$tabela .= '<th align="center"><b>Entrevistador</b></th>';
			$tabela .= '<th align="center"><b>Emergencial?</b></th>';
			$tabela .= '<th align="center"><b>Usuário do Porto?</b></th>';
			$tabela .= '<th align="center"><b>Nome do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Nome do Cônjuge da Família</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Urbano?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Urbano</b></th>';
			$tabela .= '<th align="center"><b>Bairro</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Rural?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Rural</b></th>';
			$tabela .= '<th align="center"><b>Localidade</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Telefone(s)</b></th>';
			$tabela .= '<th align="center"><b>Atendido pela ATES/Rep. Rural?</b></th>';
			$tabela .= '<th align="center"><b>Qual Benefício?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralhas?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Conteúdo</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Qtde Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 1ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 2ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 3ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 4ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Plano - Relato</b></th>';
			$tabela .= '<th align="center"><b>Plano - Plano Proposto</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Realizada?</b></th>';
			$tabela .= '<th align="center"><b>Data?</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Aceita?</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_FISH_FAMILIAS.FISH_FAM_ID, TAB_FISH_PERFILENT.FISH_PERFIL_QUEST, TAB_FISH_PERFILENT.FISH_PERFIL_PESQUISADOR, TAB_APOIO_BOOLEANO_STT_EMERG.DESCRICAO AS FISH_FAM_STT_EMERG, TAB_APOIO_BOOLEANO_STT_PORTO.DESCRICAO AS FISH_FAM_STT_PORTO, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_NOME, TAB_APOIO_BOOLEANO_ENDURB.DESCRICAO AS FISH_FAM_ENDURB, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_LOGR, TAB_APOIO_BAIRROS.DESCRICAO AS FISH_FAM_ENDURB_LOCAL, TAB_APOIO_MUNICIPIOS_URB.DESCRICAO AS FISH_FAM_ENDURB_MUNIC, TAB_APOIO_BOOLEANO_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOGR, TAB_APOIO_LOCALIDADES.DESCRICAO AS FISH_FAM_ENDRUR_LOCAL, TAB_APOIO_MUNICIPIOS_RUR.DESCRICAO AS FISH_FAM_ENDRUR_MUNIC, TAB_FISH_FAMILIAS.FISH_FAM_TELEFONES, TAB_APOIO_BOOLEANO_415421.DESCRICAO AS FISH_FAM_ATES, TAB_APOIO_BENEFICIOS.DESCRICAO AS FISH_FAM_ATES_BENEF, TAB_APOIO_BOOLEANO_E_BARCO.DESCRICAO AS FISH_PERFIL_E_BARCO, TAB_APOIO_BOOLEANO_E_BARCO_ENT.DESCRICAO AS FISH_PERFIL_E_BARCO_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENTDT, TAB_APOIO_BOOLEANO_E_MOTOR.DESCRICAO AS FISH_PERFIL_E_MOTOR, TAB_APOIO_BOOLEANO_E_MOTOR_ENT.DESCRICAO AS FISH_PERFIL_E_MOTOR_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENTDT, TAB_APOIO_BOOLEANO_E_TRALHA.DESCRICAO AS FISH_PERFIL_E_TRALHA, TAB_APOIO_BOOLEANO_E_TRALHA_ENT.DESCRICAO AS FISH_PERFIL_E_TRALHA_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_DESC, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENTDT, TAB_APOIO_BOOLEANO_E_RANCHO.DESCRICAO AS FISH_PERFIL_E_RANCHO, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENTQT AS FISH_PERFIL_E_RANCHO_QT, TAB_APOIO_BOOLEANO_E_RANCHO01.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT01, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01DT AS FISH_PERFIL_E_RANCHO_ENT01DT, TAB_APOIO_BOOLEANO_E_RANCHO02.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT02, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02DT AS FISH_PERFIL_E_RANCHO_ENT02DT, TAB_APOIO_BOOLEANO_E_RANCHO03.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT03, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03DT AS FISH_PERFIL_E_RANCHO_ENT03DT, TAB_APOIO_BOOLEANO_E_RANCHO04.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT04, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04DT AS FISH_PERFIL_E_RANCHO_ENT04DT, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_RELATO, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_ATEND, TAB_APOIO_BOOLEANO_DEVOL.DESCRICAO AS FISH_PERFIL_DEVOLUT, TAB_FISH_PERFILENT.FISH_PERFIL_DTDEVOLUT AS FISH_PERFIL_DEVOLUT_DT, TAB_APOIO_BOOLEANO_DEVOL_OK.DESCRICAO AS FISH_PERFIL_DEVOLUT_ACEITE, TAB_APOIO_STATUSATENDFISH.DESCRICAO AS FISH_PERFIL_STATUSATEND_DESC FROM TAB_FISH_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_PORTO ON TAB_FISH_FAMILIAS.FISH_FAM_STT_PORT = TAB_APOIO_BOOLEANO_STT_PORTO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_EMERG ON TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = TAB_APOIO_BOOLEANO_STT_EMERG.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB = TAB_APOIO_BOOLEANO_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_BAIRROS ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_BAIRRO = TAB_APOIO_BAIRROS.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_URB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_MUNIC = TAB_APOIO_MUNICIPIOS_URB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR = TAB_APOIO_BOOLEANO_ENDRUR.ID LEFT OUTER JOIN TAB_APOIO_LOCALIDADES ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOCAL = TAB_APOIO_LOCALIDADES.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_RUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_MUNIC = TAB_APOIO_MUNICIPIOS_RUR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_415421 ON TAB_FISH_FAMILIAS.FISH_FAM_LINK_STATUS = TAB_APOIO_BOOLEANO_415421.ID LEFT OUTER JOIN TAB_FISH_PERFILENT ON TAB_FISH_PERFILENT.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO = TAB_APOIO_BOOLEANO_E_BARCO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENT = TAB_APOIO_BOOLEANO_E_BARCO_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR = TAB_APOIO_BOOLEANO_E_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENT = TAB_APOIO_BOOLEANO_E_MOTOR_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA = TAB_APOIO_BOOLEANO_E_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENT = TAB_APOIO_BOOLEANO_E_TRALHA_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA = TAB_APOIO_BOOLEANO_E_RANCHO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO01 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01 = TAB_APOIO_BOOLEANO_E_RANCHO01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO02 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02 = TAB_APOIO_BOOLEANO_E_RANCHO02.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO03 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03 = TAB_APOIO_BOOLEANO_E_RANCHO03.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO04 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04 = TAB_APOIO_BOOLEANO_E_RANCHO04.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT = TAB_APOIO_BOOLEANO_DEVOL.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL_OK ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT_ACEITE = TAB_APOIO_BOOLEANO_DEVOL_OK.ID LEFT OUTER JOIN TAB_415421_FAMILIAS ON TAB_415421_FAMILIAS.FAMILIA_CODIGO = TAB_FISH_FAMILIAS.FISH_FAM_LINK_CODIGO LEFT OUTER JOIN TAB_APOIO_BENEFICIOS ON TAB_415421_FAMILIAS.FAMILIA_BENEFICIO = TAB_APOIO_BENEFICIOS.ID LEFT OUTER JOIN TAB_APOIO_STATUSATENDFISH ON TAB_FISH_PERFILENT.FISH_PERFIL_STATUSATEND = TAB_APOIO_STATUSATENDFISH.ID WHERE TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = 1 ORDER BY TAB_FISH_PERFILENT.FISH_PERFIL_QUEST ASC;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ID'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_STATUSATEND_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_QUEST'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_PESQUISADOR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_EMERG'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_PORTO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CHEFE_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CONJ_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ATES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ATES_BENEF'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_BARCO_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_MOTOR_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_TRALHA_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO_QT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT01DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT02DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT03DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT04DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_TRAN_RELATO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_TRAN_ATEND'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_DEVOLUT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_DEVOLUT_DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_DEVOLUT_ACEITE'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_fish_encaminhamentos_geral.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>