<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Número Questionário</b></th>';
			$tabela .= '<th align="center"><b>Entrevistador</b></th>';
//			$tabela .= '<th align="center"><b>Emergencial?</b></th>';
//			$tabela .= '<th align="center"><b>Usuário do Porto?</b></th>';
			$tabela .= '<th align="center"><b>Nome do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Apelido do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Nome do Cônjuge da Família</b></th>';
			$tabela .= '<th align="center"><b>Apelido do Cônjuge da Família</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Urbano?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Urbano</b></th>';
			$tabela .= '<th align="center"><b>Bairro</b></th>';
			$tabela .= '<th align="center"><b>Complemento</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Rural?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Rural</b></th>';
			$tabela .= '<th align="center"><b>Localidade</b></th>';
			$tabela .= '<th align="center"><b>Complemento</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Telefone(s)</b></th>';
			$tabela .= '<th align="center"><b>Atendido pela ATES/Rep. Rural?</b></th>';
			$tabela .= '<th align="center"><b>Status do Acompanhamento</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralhas?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Conteúdo</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Qtde Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 1ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 2ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 3ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da 4ª Entrega</b></th>';
			$tabela .= '<th align="center"><b>Plano - Relato</b></th>';
			$tabela .= '<th align="center"><b>Plano - Plano Proposto</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Realizada?</b></th>';
			$tabela .= '<th align="center"><b>Data?</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Aceita?</b></th>';
			$tabela .= '<th align="center"><b>B2 - Estava Pescando?</b></th>';
			$tabela .= '<th align="center"><b>B3 - Qts. Pescarias/Mês</b></th>';
			$tabela .= '<th align="center"><b>B4 - Média Dias/Pescaria</b></th>';
			$tabela .= '<th align="center"><b>B5 - Total Dias Pescando</b></th>';			
			$tabela .= '<th align="center"><b>B6 - Média Pessoas/Pescaria</b></th>';
			$tabela .= '<th align="center"><b>B7 - Média KG Pescado na Temporada</b></th>';			
			$tabela .= '<th align="center"><b>B8 - Média KG Pescado Fora da Temporada</b></th>';
			$tabela .= '<th align="center"><b>B9 - Vendia Parte ou Toda Produção?</b></th>';			
			$tabela .= '<th align="center"><b>B10 - Média KG Vendido</b></th>';
			$tabela .= '<th align="center"><b>B11 - Valor Médio R$</b></th>';			
			$tabela .= '<th align="center"><b>B13 - Média KG Consumido</b></th>';
			$tabela .= '<th align="center"><b>Campanha</b></th>';			
			$tabela .= '<th align="center"><b>Técnico Responsável</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrevista</b></th>';			
			$tabela .= '<th align="center"><b>Data da Entrevista Anterior</b></th>';
			$tabela .= '<th align="center"><b>Intervalo de Dias</b></th>';			
			$tabela .= '<th align="center"><b>Realizou Pescaria?</b></th>';
			$tabela .= '<th align="center"><b>Qtas Pescarias?</b></th>';			
			$tabela .= '<th align="center"><b>Média Dias/Pescaria</b></th>';
			$tabela .= '<th align="center"><b>Totas Dias/Pescando</b></th>';			
			$tabela .= '<th align="center"><b>Média Pessoas/Pescaria</b></th>';
			$tabela .= '<th align="center"><b>Utilizou Equipamentos?</b></th>';			
			$tabela .= '<th align="center"><b>Porque não utilizou os equipamentos?</b></th>';
			$tabela .= '<th align="center"><b>Mudou local da Pesca?</b></th>';			
			$tabela .= '<th align="center"><b>Novo local é melhor?</b></th>';
			$tabela .= '<th align="center"><b>Melhorou os resultados?</b></th>';			
			$tabela .= '<th align="center"><b>Mudaram as espécies?</b></th>';
			$tabela .= '<th align="center"><b>Melhoraram as condições de vida?</b></th>';			
			$tabela .= '<th align="center"><b>Média KG Pescado/Pescaria</b></th>';
			$tabela .= '<th align="center"><b>A produção foi vendida?</b></th>';			
			$tabela .= '<th align="center"><b>Média KG Pescado Vendido</b></th>';
			$tabela .= '<th align="center"><b>Valor Médi de Venda R$</b></th>';			
			$tabela .= '<th align="center"><b>Média KG Pescado Consumido</b></th>';
			$tabela .= '<th align="center"><b>Se não pescou, Porque?</b></th>';			
			$tabela .= '<th align="center"><b>Satisfeito com os equipamentos?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, porque?</b></th>';			
			$tabela .= '<th align="center"><b>Satisfeito com o atendimento?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, porque?</b></th>';			
			$tabela .= '<th align="center"><b>Vai se filiar a cooperativa?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, porque?</b></th>';			
			$tabela .= '<th align="center"><b>Preenchendo as Fichas de Acompanhamento?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, porque?</b></th>';			
			$tabela .= '<th align="center"><b>Motor Vistoriado?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';			
			$tabela .= '<th align="center"><b>Bom estado de conservação?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';			
			$tabela .= '<th align="center"><b>Estava em posse do Pescador?</b></th>';
			$tabela .= '<th align="center"><b>Embarcação Vistoriada?</b></th>';			
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Bom estado de conservação?</b></th>';			
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Estava em posse do Pescador?</b></th>';			
			$tabela .= '<th align="center"><b>Tralha Vistoriada?</b></th>';
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';			
			$tabela .= '<th align="center"><b>Bom estado de conservação?</b></th>';			
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Estava em posse do Pescador?</b></th>';
			$tabela .= '<th align="center"><b>Evicências que está pescando?</b></th>';			
			$tabela .= '<th align="center"><b>Se NÃO, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Evidências de venda do equipamento?</b></th>';			
			$tabela .= '<th align="center"><b>Se SIM, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Evidências de falsidade nas respostas?</b></th>';			
			$tabela .= '<th align="center"><b>Se SIM, Porque?</b></th>';
			$tabela .= '<th align="center"><b>Percepções do Entrevistador</b></th>';			
			$tabela .= '<th align="center"><b>Observações Gerais</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_FISH_FAMILIAS.FISH_FAM_ID, TAB_FISH_PERFILENT.FISH_PERFIL_QUEST, TAB_FISH_PERFILENT.FISH_PERFIL_PESQUISADOR, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_NOME, TAB_APOIO_BOOLEANO_ENDURB.DESCRICAO AS FISH_FAM_ENDURB, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_LOGR, TAB_APOIO_BAIRROS.DESCRICAO AS FISH_FAM_ENDURB_LOCAL, TAB_APOIO_MUNICIPIOS_URB.DESCRICAO AS FISH_FAM_ENDURB_MUNIC, TAB_APOIO_BOOLEANO_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOGR, TAB_APOIO_LOCALIDADES.DESCRICAO AS FISH_FAM_ENDRUR_LOCAL, TAB_APOIO_MUNICIPIOS_RUR.DESCRICAO AS FISH_FAM_ENDRUR_MUNIC, TAB_FISH_FAMILIAS.FISH_FAM_TELEFONES, TAB_APOIO_BOOLEANO_415421.DESCRICAO AS FISH_FAM_ATES, TAB_APOIO_BOOLEANO_E_BARCO.DESCRICAO AS FISH_PERFIL_E_BARCO, TAB_APOIO_BOOLEANO_E_BARCO_ENT.DESCRICAO AS FISH_PERFIL_E_BARCO_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENTDT, TAB_APOIO_BOOLEANO_E_MOTOR.DESCRICAO AS FISH_PERFIL_E_MOTOR, TAB_APOIO_BOOLEANO_E_MOTOR_ENT.DESCRICAO AS FISH_PERFIL_E_MOTOR_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENTDT, TAB_APOIO_BOOLEANO_E_TRALHA.DESCRICAO AS FISH_PERFIL_E_TRALHA, TAB_APOIO_BOOLEANO_E_TRALHA_ENT.DESCRICAO AS FISH_PERFIL_E_TRALHA_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_DESC, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENTDT, TAB_APOIO_BOOLEANO_E_RANCHO.DESCRICAO AS FISH_PERFIL_E_RANCHO, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENTQT AS FISH_PERFIL_E_RANCHO_QT, TAB_APOIO_BOOLEANO_E_RANCHO01.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT01, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01DT AS FISH_PERFIL_E_RANCHO_ENT01DT, TAB_APOIO_BOOLEANO_E_RANCHO02.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT02, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02DT AS FISH_PERFIL_E_RANCHO_ENT02DT, TAB_APOIO_BOOLEANO_E_RANCHO03.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT03, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03DT AS FISH_PERFIL_E_RANCHO_ENT03DT, TAB_APOIO_BOOLEANO_E_RANCHO04.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT04, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04DT AS FISH_PERFIL_E_RANCHO_ENT04DT, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_RELATO, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_ATEND, TAB_APOIO_BOOLEANO_DEVOL.DESCRICAO AS FISH_PERFIL_DEVOLUT, TAB_FISH_PERFILENT.FISH_PERFIL_DTDEVOLUT AS FISH_PERFIL_DEVOLUT_DT, TAB_APOIO_BOOLEANO_DEVOL_OK.DESCRICAO AS FISH_PERFIL_DEVOLUT_ACEITE, TAB_APOIO_BOOLEANO_ACOMP_ANTES_01.DESCRICAO AS FISH_AA_BOO_PESCAVA_DESC, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_QTMES, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_QTINT, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_QTDIAS, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_QTPESSOAS, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_PRODTEMP, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_PRODFTEMP, TAB_APOIO_BOOLEANO_ACOMP_ANTES_02.DESCRICAO AS FISH_AA_BOO_PESCA_VENDIA_DESC, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_PRODVENDA, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_QT_PESCA_PRODCOSUMO, TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_VL_PESCA_PRODMEDIA, TAB_FISH_CAMPANHAS.FISH_CAMP_DESCRICAO AS FISH_AE_CAMPANHA_DESC, TAB_APOIO_TECNICOS.DESCRICAO AS FISH_AE_TECNICO_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_DT_ENTR_ATUAL, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_DT_ENTR_ANTERIOR, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_ENTR_INTERVDIAS, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_01.DESCRICAO AS FISH_AE_BOO_PESCA_REALIZOU_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_QTDEPESCARIAS, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_MEDIADIASPESCARIAS, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_TOTALDIASPESCARIAS, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_02.DESCRICAO AS FISH_AE_BOO_PESCA_USOUEQUIPS, TAB_APOIO_PESCA_EQUIPNUSO.DESCRICAO AS FISH_AE_FK_PESCA_NUSOUEQUIPS_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_03.DESCRICAO AS FISH_AE_BOO_PESCA_LOCALMUDOU_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_04.DESCRICAO AS FISH_AE_BOO_PESCA_LOCALMELHOR_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_05.DESCRICAO AS FISH_AE_BOO_PESCA_RESULTMELHOR_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_06.DESCRICAO AS FISH_AE_BOO_PESCA_ESPECIESMUDOU_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_07.DESCRICAO AS FISH_AE_BOO_PESCA_CONDVIDAMELHOR_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_MEDIAKQPESCARIA, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_08.DESCRICAO AS FISH_AE_BOO_PESCA_PRODVENDIDA_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_MEDIAKQVENDIDO, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_VL_PESCA_VALORKQVENDIDO, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_QT_PESCA_MEDIAKQCONSUMO, TAB_APOIO_PESCA_MOTIVO.DESCRICAO AS FISH_AE_FK_PESCA_NENHUMAPESCARIA_DESC, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_09.DESCRICAO AS FISH_AE_BOO_PESCA_SATISFACAO_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_TXT_PESCA_SATISFACAO, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_10.DESCRICAO AS FISH_AE_BOO_ATEND_SATISFACAO_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_TXT_ATEND_SATISFACAO, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_11.DESCRICAO AS FISH_AE_BOO_COOP_FILIACAO_DESC, TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_TXT_COOP_FILIACAO, TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_12.DESCRICAO AS FISH_AE_BOO_PESCA_FICHASOK_DESC, TAB_APOIO_PESCA_FICHASNPREENC.DESCRICAO AS FISH_AE_FK_PESCA_FICHASMOTIVO_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_ID, TAB_APOIO_BOO_ACOMP_PERCEP_VIST_MOTOR.DESCRICAO AS FISH_AP_BOO_MOTOR_DESC, TAB_APOIO_FK_ACOMP_PERCEP_NVIST_MOTOR.DESCRICAO AS FISH_AP_FK_MOTORNVIST_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_MOTOR.DESCRICAO AS FISH_AP_BOO_MOTORCONSERV_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_MOTORCONSERV, TAB_APOIO_FK_ACOMP_PERCEP_POSSE_MOTOR.DESCRICAO AS FISH_AP_FK_MOTORPOSSE_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_VIST_EMBARC.DESCRICAO AS FISH_AP_BOO_EMBARC_DESC, TAB_APOIO_FK_ACOMP_PERCEP_NVIST_EMBARC.DESCRICAO AS FISH_AP_FK_EMBARCNVIST_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_EMBARC.DESCRICAO AS FISH_AP_BOO_EMBARCCONSERV_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_EMBARCCONSERV, TAB_APOIO_FK_ACOMP_PERCEP_POSSE_EMBARC.DESCRICAO AS FISH_AP_FK_EMBARCPOSSE_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_VIST_TRALHA.DESCRICAO AS FISH_AP_BOO_TRALHA_DESC, TAB_APOIO_FK_ACOMP_PERCEP_NVIST_TRALHA.DESCRICAO AS FISH_AP_FK_TRALHANVIST_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_TRALHA.DESCRICAO AS FISH_AP_BOO_TRALHACONSERV_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_TRALHACONSERV, TAB_APOIO_FK_ACOMP_PERCEP_POSSE_TRALHA.DESCRICAO AS FISH_AP_FK_TRALHAPOSSE_DESC, TAB_APOIO_BOO_ACOMP_PERCEP_EVID_PESCA.DESCRICAO AS FISH_AP_BOO_EVIDPESCANDO_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_EVIDPESCANDO, TAB_APOIO_BOO_ACOMP_PERCEP_EVID_VENDA.DESCRICAO AS FISH_AP_BOO_EVIDVENDA_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_EVIDVENDA, TAB_APOIO_BOO_ACOMP_PERCEP_EVID_FALSIDADE.DESCRICAO AS FISH_AP_BOO_EVIDFALSIDADE_DESC, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_EVIDFALSIDADE, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_PERCEPCOES, TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_TXT_OBSERVACOES, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_APELIDO, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_APELIDO, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_COMPL, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_COMPL, TAB_APOIO_STATUSATENDFISH.DESCRICAO AS FISH_PERFIL_STATUSATEND_DESC FROM TAB_FISH_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB = TAB_APOIO_BOOLEANO_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_BAIRROS ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_BAIRRO = TAB_APOIO_BAIRROS.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_URB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_MUNIC = TAB_APOIO_MUNICIPIOS_URB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR = TAB_APOIO_BOOLEANO_ENDRUR.ID LEFT OUTER JOIN TAB_APOIO_LOCALIDADES ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOCAL = TAB_APOIO_LOCALIDADES.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_RUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_MUNIC = TAB_APOIO_MUNICIPIOS_RUR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_415421 ON TAB_FISH_FAMILIAS.FISH_FAM_LINK_STATUS = TAB_APOIO_BOOLEANO_415421.ID LEFT OUTER JOIN TAB_FISH_PERFILENT ON TAB_FISH_PERFILENT.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO = TAB_APOIO_BOOLEANO_E_BARCO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENT = TAB_APOIO_BOOLEANO_E_BARCO_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR = TAB_APOIO_BOOLEANO_E_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENT = TAB_APOIO_BOOLEANO_E_MOTOR_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA = TAB_APOIO_BOOLEANO_E_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENT = TAB_APOIO_BOOLEANO_E_TRALHA_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA = TAB_APOIO_BOOLEANO_E_RANCHO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO01 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01 = TAB_APOIO_BOOLEANO_E_RANCHO01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO02 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02 = TAB_APOIO_BOOLEANO_E_RANCHO02.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO03 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03 = TAB_APOIO_BOOLEANO_E_RANCHO03.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO04 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04 = TAB_APOIO_BOOLEANO_E_RANCHO04.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT = TAB_APOIO_BOOLEANO_DEVOL.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL_OK ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT_ACEITE = TAB_APOIO_BOOLEANO_DEVOL_OK.ID LEFT OUTER JOIN TAB_FISH_ACOMP_ANTESTRANS ON TAB_FISH_ACOMP_ANTESTRANS.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ANTES_01 ON TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_BOO_PESCAVA = TAB_APOIO_BOOLEANO_ACOMP_ANTES_01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ANTES_02 ON TAB_FISH_ACOMP_ANTESTRANS.FISH_AA_BOO_PESCA_VENDIA = TAB_APOIO_BOOLEANO_ACOMP_ANTES_02.ID LEFT OUTER JOIN TAB_FISH_ACOMP_ENTREVISTA ON TAB_FISH_ACOMP_ENTREVISTA.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_FISH_CAMPANHAS ON TAB_FISH_CAMPANHAS.FISH_CAMP_ID = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_CAMPANHA LEFT OUTER JOIN TAB_APOIO_TECNICOS ON TAB_APOIO_TECNICOS.ID = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_TECNICO LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_01 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_REALIZOU = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_02 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_USOUEQUIPS = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_02.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_03 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_LOCALMUDOU = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_03.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_04 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_LOCALMELHOR = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_04.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_05 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_RESULTMELHOR = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_05.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_06 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_ESPECIESMUDOU = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_06.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_07 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_CONDVIDAMELHOR = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_07.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_08 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_PRODVENDIDA = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_08.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_09 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_SATISFACAO = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_09.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_10 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_ATEND_SATISFACAO = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_10.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_11 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_COOP_FILIACAO = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_11.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_12 ON TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_BOO_PESCA_FICHASOK = TAB_APOIO_BOOLEANO_ACOMP_ENTREVISTA_12.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPNUSO ON TAB_APOIO_PESCA_EQUIPNUSO.ID = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_FK_PESCA_NUSOUEQUIPS LEFT OUTER JOIN TAB_APOIO_PESCA_MOTIVO ON TAB_APOIO_PESCA_MOTIVO.ID = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_FK_PESCA_NENHUMAPESCARIA LEFT OUTER JOIN TAB_APOIO_PESCA_FICHASNPREENC ON TAB_APOIO_PESCA_FICHASNPREENC.ID = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_FK_PESCA_FICHASMOTIVO LEFT OUTER JOIN TAB_FISH_ACOMP_PERCEPCAO ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AEP_AE = TAB_FISH_ACOMP_ENTREVISTA.FISH_AE_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_VIST_MOTOR ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_MOTOR = TAB_APOIO_BOO_ACOMP_PERCEP_VIST_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPNVIST AS TAB_APOIO_FK_ACOMP_PERCEP_NVIST_MOTOR ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_MOTORNVIST = TAB_APOIO_FK_ACOMP_PERCEP_NVIST_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_MOTOR ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_MOTORCONSERV = TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPPOSSE AS TAB_APOIO_FK_ACOMP_PERCEP_POSSE_MOTOR ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_MOTORPOSSE = TAB_APOIO_FK_ACOMP_PERCEP_POSSE_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_VIST_EMBARC ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_EMBARC = TAB_APOIO_BOO_ACOMP_PERCEP_VIST_EMBARC.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPNVIST AS TAB_APOIO_FK_ACOMP_PERCEP_NVIST_EMBARC ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_EMBARCNVIST = TAB_APOIO_FK_ACOMP_PERCEP_NVIST_EMBARC.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_EMBARC ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_EMBARCCONSERV = TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_EMBARC.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPPOSSE AS TAB_APOIO_FK_ACOMP_PERCEP_POSSE_EMBARC ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_EMBARCPOSSE = TAB_APOIO_FK_ACOMP_PERCEP_POSSE_EMBARC.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_VIST_TRALHA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_TRALHA = TAB_APOIO_BOO_ACOMP_PERCEP_VIST_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPNVIST AS TAB_APOIO_FK_ACOMP_PERCEP_NVIST_TRALHA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_TRALHANVIST = TAB_APOIO_FK_ACOMP_PERCEP_NVIST_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_TRALHA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_TRALHACONSERV = TAB_APOIO_BOO_ACOMP_PERCEP_CONSERV_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_PESCA_EQUIPPOSSE AS TAB_APOIO_FK_ACOMP_PERCEP_POSSE_TRALHA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_FK_TRALHAPOSSE = TAB_APOIO_FK_ACOMP_PERCEP_POSSE_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_EVID_PESCA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_EVIDPESCANDO = TAB_APOIO_BOO_ACOMP_PERCEP_EVID_PESCA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_EVID_VENDA ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_EVIDVENDA = TAB_APOIO_BOO_ACOMP_PERCEP_EVID_VENDA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOO_ACOMP_PERCEP_EVID_FALSIDADE ON TAB_FISH_ACOMP_PERCEPCAO.FISH_AP_BOO_EVIDFALSIDADE = TAB_APOIO_BOO_ACOMP_PERCEP_EVID_FALSIDADE.ID LEFT OUTER JOIN TAB_APOIO_STATUSATENDFISH ON TAB_FISH_PERFILENT.FISH_PERFIL_STATUSATEND = TAB_APOIO_STATUSATENDFISH.ID WHERE TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = 1 ORDER BY TAB_FISH_PERFILENT.FISH_PERFIL_QUEST ASC;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ID'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_QUEST'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_PESQUISADOR'].'</td>';
//				$tabela .= '<td>'.$vetor['FISH_FAM_STT_EMERG'].'</td>';
//				$tabela .= '<td>'.$vetor['FISH_FAM_STT_PORTO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CHEFE_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CHEFE_APELIDO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CONJ_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CONJ_APELIDO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_COMPL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_COMPL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ATES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_STATUSATEND_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_BARCO_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_MOTOR_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_TRALHA_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO_QT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT01DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT02DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT03DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT04DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_TRAN_RELATO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_TRAN_ATEND'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_DEVOLUT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_DEVOLUT_DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_DEVOLUT_ACEITE'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_BOO_PESCAVA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_QT_PESCA_QTMES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_QT_PESCA_QTINT'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_QT_PESCA_QTDIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_QT_PESCA_QTPESSOAS'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AA_QT_PESCA_PRODTEMP'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AA_QT_PESCA_PRODFTEMP'],2,',','.').'</td>';
				$tabela .= '<td>'.$vetor['FISH_AA_BOO_PESCA_VENDIA_DESC'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AA_QT_PESCA_PRODVENDA'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AA_VL_PESCA_PRODMEDIA'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AA_QT_PESCA_PRODCOSUMO'],2,',','.').'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_CAMPANHA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_TECNICO_DESC'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_AE_DT_ENTR_ATUAL'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_AE_DT_ENTR_ANTERIOR'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_QT_ENTR_INTERVDIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_REALIZOU_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_QT_PESCA_QTDEPESCARIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_QT_PESCA_MEDIADIASPESCARIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_QT_PESCA_TOTALDIASPESCARIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_USOUEQUIPS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_FK_PESCA_NUSOUEQUIPS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_LOCALMUDOU_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_LOCALMELHOR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_RESULTMELHOR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_ESPECIESMUDOU_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_CONDVIDAMELHOR_DESC'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AE_QT_PESCA_MEDIAKQPESCARIA'],2,',','.').'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_PRODVENDIDA_DESC'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AE_QT_PESCA_MEDIAKQVENDIDO'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AE_VL_PESCA_VALORKQVENDIDO'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_AE_QT_PESCA_MEDIAKQCONSUMO'],2,',','.').'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_FK_PESCA_NENHUMAPESCARIA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_SATISFACAO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_TXT_PESCA_SATISFACAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_ATEND_SATISFACAO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_TXT_ATEND_SATISFACAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_COOP_FILIACAO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_TXT_COOP_FILIACAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_BOO_PESCA_FICHASOK_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AE_FK_PESCA_FICHASMOTIVO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_MOTOR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_MOTORNVIST_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_MOTORCONSERV_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_MOTORCONSERV'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_MOTORPOSSE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_EMBARC_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_EMBARCNVIST_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_EMBARCCONSERV_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_EMBARCCONSERV'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_EMBARCPOSSE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_TRALHA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_TRALHANVIST_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_TRALHACONSERV_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_TRALHACONSERV'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_FK_TRALHAPOSSE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_EVIDPESCANDO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_EVIDPESCANDO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_EVIDVENDA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_EVIDVENDA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_BOO_EVIDFALSIDADE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_EVIDFALSIDADE'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_PERCEPCOES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_AP_TXT_OBSERVACOES'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_fish_acomp_completo.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>