<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Nome do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Nome do Cônjuge da Família</b></th>';
			$tabela .= '<th align="center"><b>Participou do Diagnóstico?</b></th>';
			$tabela .= '<th align="center"><b>Emergencial?</b></th>';
			$tabela .= '<th align="center"><b>Usuário do Porto?</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Urbano?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Urbano</b></th>';
			$tabela .= '<th align="center"><b>Bairro</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Uso do Imóvel Urbano</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Rural?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Rural</b></th>';
			$tabela .= '<th align="center"><b>Localidade</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Uso do Imóvel Rural</b></th>';
			$tabela .= '<th align="center"><b>Telefone(s)</b></th>';
			$tabela .= '<th align="center"><b>Atendido pela ATES/Rep. Rural?</b></th>';
			$tabela .= '<th align="center"><b>Tipo do Benefício</b></th>';
			$tabela .= '<th align="center"><b>Número Questionário</b></th>';
			$tabela .= '<th align="center"><b>Data da Entrevista</b></th>';
			$tabela .= '<th align="center"><b>Local da Entrevista</b></th>';
			$tabela .= '<th align="center"><b>Atividade Econômica Principal</b></th>';
			$tabela .= '<th align="center"><b>Atividade Econômica Secundária</b></th>';
			$tabela .= '<th align="center"><b>Número de Pessoas na Família</b></th>';
			$tabela .= '<th align="center"><b>Número de Pescadores na Família</b></th>';
			$tabela .= '<th align="center"><b>Pratica Atividade de Pesca?</b></th>';
			$tabela .= '<th align="center"><b>Tempo de Atividade</b></th>';
			$tabela .= '<th align="center"><b>Tipo da Atividade de Pesca</b></th>';
			$tabela .= '<th align="center"><b>Atendido por Projetos da NESA?</b></th>';
			$tabela .= '<th align="center"><b>Possui Outras Rendas?</b></th>';
			$tabela .= '<th align="center"><b>Possui Benefícios Sociais?</b></th>';
			$tabela .= '<th align="center"><b>Pratica Agricultura?</b></th>';
			$tabela .= '<th align="center"><b>Comercializa a Produção?</b></th>';
			$tabela .= '<th align="center"><b>Área da Produção</b></th>';
			$tabela .= '<th align="center"><b>Número de Pesoas na Agricultura</b></th>';
			$tabela .= '<th align="center"><b>Detalhamento da Produção</b></th>';
			$tabela .= '<th align="center"><b>Consumo da Proteína - Peixes</b></th>';
			$tabela .= '<th align="center"><b>Observações Gerais</b></th>';
			$tabela .= '<th align="center"><b>Pescando atualmente?</b></th>';
			$tabela .= '<th align="center"><b>Se não, porque?</b></th>';
			$tabela .= '<th align="center"><b>Pesca sozinho?</b></th>';
			$tabela .= '<th align="center"><b>Com quantas pessoas?</b></th>';
			$tabela .= '<th align="center"><b>Da família?</b></th>';
			$tabela .= '<th align="center"><b>Pesca ornamental?</b></th>';
			$tabela .= '<th align="center"><b>Pesca peixe de consumo?</b></th>';
			$tabela .= '<th align="center"><b>Destino do peixe de consumo?</b></th>';
			$tabela .= '<th align="center"><b>Média de dias das pescarias</b></th>';
			$tabela .= '<th align="center"><b>Média de pescarias o mês</b></th>';
			$tabela .= '<th align="center"><b>Média de KG fora do defeso</b></th>';
			$tabela .= '<th align="center"><b>Média de KG no defeso</b></th>';
			$tabela .= '<th align="center"><b>Despesas - Combustível</b></th>';
			$tabela .= '<th align="center"><b>Despesas - Gelo</b></th>';
			$tabela .= '<th align="center"><b>Despesas - Rancho</b></th>';
			$tabela .= '<th align="center"><b>Despesas - Outro(s)</b></th>';
			$tabela .= '<th align="center"><b>Usa Canoa?</b></th>';
			$tabela .= '<th align="center"><b>Quantas?</b></th>';
			$tabela .= '<th align="center"><b>Usa Barco Próprio?</b></th>';
			$tabela .= '<th align="center"><b>Quantos?</b></th>';
			$tabela .= '<th align="center"><b>Usa Barco Emprestado/Alugado?</b></th>';
			$tabela .= '<th align="center"><b>Quantos?</b></th>';
			$tabela .= '<th align="center"><b>Usa Motor Próprio?</b></th>';
			$tabela .= '<th align="center"><b>Quantos?</b></th>';
			$tabela .= '<th align="center"><b>Usa Motor Emprestado/Alugado?</b></th>';
			$tabela .= '<th align="center"><b>Quantos?</b></th>';
			$tabela .= '<th align="center"><b>Participa de alguma entidade?</b></th>';
			$tabela .= '<th align="center"><b>Quais?</b></th>';
			$tabela .= '<th align="center"><b>Dificuldades da Atividade Econômica</b></th>';
			$tabela .= '<th align="center"><b>Perspectiva da Cooperativa</b></th>';
			$tabela .= '<th align="center"><b>Pretende se Filiar?</b></th>';
			$tabela .= '<th align="center"><b>Se sim, porque?</b></th>';
			$tabela .= '<th align="center"><b>Se não, porque?</b></th>';
			$tabela .= '<th align="center"><b>Percepção do Técnico</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_FISH_FAMILIAS.FISH_FAM_ID, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_NOME, TAB_APOIO_BOOLEANO_STT_OFIC.DESCRICAO AS FISH_FAM_STT_OFIC_DESC, TAB_APOIO_BOOLEANO_STT_EMER.DESCRICAO AS FISH_FAM_STT_EMER_DESC, TAB_APOIO_BOOLEANO_STT_PORT.DESCRICAO AS FISH_FAM_STT_PORT_DESC, TAB_APOIO_BOOLEANO_STT_COOP.DESCRICAO AS FISH_FAM_STT_COOP_DESC, TAB_APOIO_BOOLEANO_ENDURB.DESCRICAO AS FISH_FAM_ENDURB_DESC, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_LOGR, TAB_APOIO_BAIRROS.DESCRICAO AS  FISH_FAM_ENDURB_BAIRRO_DESC, TAB_APOIO_MUNICIPIOS_ENDURB.DESCRICAO AS FISH_FAM_ENDURB_MUNIC_DESC, TAB_APOIO_USOIMOVEL_ENDURB.DESCRICAO AS FISH_FAM_ENDURB_USO_DESC, TAB_APOIO_BOOLEANO_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR_DESC, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOGR, TAB_APOIO_LOCALIDADES.DESCRICAO AS FISH_FAM_ENDRUR_LOCAL_DESC, TAB_APOIO_MUNICIPIOS_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR_MUNIC_DESC, TAB_APOIO_USOIMOVEL_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR_USO_DESC, TAB_FISH_FAMILIAS.FISH_FAM_TELEFONES, TAB_APOIO_BOOLEANO_LINK.DESCRICAO AS FISH_FAM_LINK_STATUS_DESC, TAB_APOIO_BENEFICIOS.DESCRICAO AS FISH_FAM_LINK_BENEFICIO_DESC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_QUEST, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_DTENTREVISTA, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_LOCENTREVISTA, TAB_APOIO_ATIVECONOMICA_PRINC.DESCRICAO AS FISH_COOP_ATIVPRINCIPAL_DESC, TAB_APOIO_ATIVECONOMICA_SECND.DESCRICAO AS FISH_COOP_ATIVSECUNDARIA_DESC, VIEW_FISH_FAMILIA_COMPONENTES.FISH_FAM_COUNT_PESSOAS, VIEW_FISH_FAMILIA_PESCADORES.FISH_FAM_COUNT_PESCADORES, TAB_APOIO_BOOLEANO_ATIVPESCA.DESCRICAO AS FISH_COOP_ATIVPESCA_DESC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVPESCATEMPO, TAB_APOIO_UNIDMED_TEMPO.DESCRICAO AS FISH_COOP_ATIVPESCAUNIT_DESC, TAB_APOIO_ATIVPESCA.DESCRICAO AS FISH_COOP_ATIVPESCATIPO_DESC, TAB_APOIO_BOOLEANO_PROJETONESA.DESCRICAO AS FISH_COOP_PROJETONESA_DESC, TAB_APOIO_BOOLEANO_OUTRASRENDAS.DESCRICAO AS FISH_COOP_OUTRASRENDAS_DESC, TAB_APOIO_BOOLEANO_BENEFSOCIAIS.DESCRICAO AS FISH_COOP_BENEFSOCIAIS_DESC, TAB_APOIO_BOOLEANO_AGRICULTURA.DESCRICAO AS FISH_COOP_AGRICULTURA_DESC, TAB_APOIO_BOOLEANO_AGRICCOMERCIO.DESCRICAO AS FISH_COOP_AGRICCOMERCIO_DESC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICAREA, TAB_APOIO_UNIDMED_TAMANHO.DESCRICAO AS FISH_COOP_AGRICUNIT_DESC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICPESSOAS, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICDESCRICAO, TAB_APOIO_FREQCONSUMPROT.DESCRICAO AS FISH_COOP_CONSUMOPEIXE_DESC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_OBSERVACOES, TAB_APOIO_BOOLEANO_CARACT_PESCANDO.DESCRICAO AS FISH_COOCAR_PESCANDO_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_MOTIVO, TAB_APOIO_BOOLEANO_CARACT_SOZINHO.DESCRICAO AS FISH_COOCAR_SOZINHO_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_QTS_PESSOAS, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_QTS_FAMILIA, TAB_APOIO_BOOLEANO_CARACT_ORNAMENTAL.DESCRICAO AS FISH_COOCAR_ORNAMENTAL_DESC, TAB_APOIO_BOOLEANO_CARACT_CONSUMO.DESCRICAO AS FISH_COOCAR_CONSUMO_DESC, TAB_APOIO_PESCA_TIPO.DESCRICAO AS FISH_COOCAR_DESTINO_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DIAS, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_VEZES, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_KG_FORADEFESO, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_KG_DENTRODEFESO, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DESP_COMBS, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DESP_GELO, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DESP_RANCHO, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DESP_OUTROS, TAB_APOIO_BOOLEANO_CANOA_PROP.DESCRICAO AS FISH_COOCAR_CANOA_PROP_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_CANOA_PROP_QTS, TAB_APOIO_BOOLEANO_BARCO_PROP.DESCRICAO AS FISH_COOCAR_BARCO_PROP_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_BARCO_PROP_QTS, TAB_APOIO_BOOLEANO_BARCO_ALUG.DESCRICAO AS FISH_COOCAR_BARCO_ALUG_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_BARCO_ALUG_QTS, TAB_APOIO_BOOLEANO_MOTOR_PROP.DESCRICAO AS FISH_COOCAR_MOTOR_PROP_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_MOTOR_PROP_QTS, TAB_APOIO_BOOLEANO_MOTOR_ALUG.DESCRICAO AS FISH_COOCAR_MOTOR_ALUG_DESC, TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_MOTOR_ALUG_QTS, TAB_APOIO_BOOLEANO_EXPEC_PART.DESCRICAO AS FISH_COOEXP_PART_DESC, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_PART_QUAL, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_DIFICULDADES, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_CONTRIBUICAO, TAB_APOIO_BOOLEANO_EXPEC_FILIACAO.DESCRICAO AS FISH_COOEXP_FILIACAO_DESC, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_FILI_SIM, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_FILI_NAO, TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_PERCEPCAO FROM TAB_FISH_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_OFIC ON TAB_FISH_FAMILIAS.FISH_FAM_STT_OFIC = TAB_APOIO_BOOLEANO_STT_OFIC.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_EMER ON TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = TAB_APOIO_BOOLEANO_STT_EMER.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_COOP ON TAB_FISH_FAMILIAS.FISH_FAM_STT_COOP = TAB_APOIO_BOOLEANO_STT_COOP.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_PORT ON TAB_FISH_FAMILIAS.FISH_FAM_STT_PORT = TAB_APOIO_BOOLEANO_STT_PORT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB = TAB_APOIO_BOOLEANO_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR = TAB_APOIO_BOOLEANO_ENDRUR.ID LEFT OUTER JOIN TAB_FISH_COOP_ENTREVISTA ON TAB_FISH_COOP_ENTREVISTA.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BAIRROS ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_BAIRRO = TAB_APOIO_BAIRROS.ID LEFT OUTER JOIN TAB_APOIO_LOCALIDADES ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOCAL = TAB_APOIO_LOCALIDADES.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_MUNIC = TAB_APOIO_MUNICIPIOS_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_MUNIC = TAB_APOIO_MUNICIPIOS_ENDRUR.ID LEFT OUTER JOIN TAB_APOIO_USOIMOVEL AS TAB_APOIO_USOIMOVEL_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_USO = TAB_APOIO_USOIMOVEL_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_USOIMOVEL AS TAB_APOIO_USOIMOVEL_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_USO = TAB_APOIO_USOIMOVEL_ENDRUR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_LINK ON TAB_FISH_FAMILIAS.FISH_FAM_LINK_STATUS = TAB_APOIO_BOOLEANO_LINK.ID LEFT OUTER JOIN TAB_415421_FAMILIAS ON TAB_415421_FAMILIAS.FAMILIA_CODIGO = TAB_FISH_FAMILIAS.FISH_FAM_LINK_CODIGO LEFT OUTER JOIN TAB_APOIO_BENEFICIOS ON TAB_415421_FAMILIAS.FAMILIA_BENEFICIO = TAB_APOIO_BENEFICIOS.ID LEFT OUTER JOIN TAB_APOIO_ATIVECONOMICA AS TAB_APOIO_ATIVECONOMICA_PRINC ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVPRINCIPAL = TAB_APOIO_ATIVECONOMICA_PRINC.ID LEFT OUTER JOIN TAB_APOIO_ATIVECONOMICA AS TAB_APOIO_ATIVECONOMICA_SECND ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVSECUNDARIA = TAB_APOIO_ATIVECONOMICA_SECND.ID LEFT OUTER JOIN VIEW_FISH_FAMILIA_COMPONENTES ON VIEW_FISH_FAMILIA_COMPONENTES.FISH_FAM_ID = TAB_FISH_COOP_ENTREVISTA.FISH_FAM_ID LEFT OUTER JOIN VIEW_FISH_FAMILIA_PESCADORES ON VIEW_FISH_FAMILIA_PESCADORES.FISH_FAM_ID = TAB_FISH_COOP_ENTREVISTA.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ATIVPESCA ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVPESCA = TAB_APOIO_BOOLEANO_ATIVPESCA.ID LEFT OUTER JOIN TAB_APOIO_UNIDMED_TEMPO ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVPESCAUNIT = TAB_APOIO_UNIDMED_TEMPO.ID LEFT OUTER JOIN TAB_APOIO_ATIVPESCA ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_ATIVPESCATIPO = TAB_APOIO_ATIVPESCA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_PROJETONESA ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_PROJETONESA = TAB_APOIO_BOOLEANO_PROJETONESA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_OUTRASRENDAS ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_OUTRASRENDAS = TAB_APOIO_BOOLEANO_OUTRASRENDAS.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_BENEFSOCIAIS ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_BENEFSOCIAIS = TAB_APOIO_BOOLEANO_BENEFSOCIAIS.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_AGRICULTURA ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICULTURA = TAB_APOIO_BOOLEANO_AGRICULTURA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_AGRICCOMERCIO ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICCOMERCIO = TAB_APOIO_BOOLEANO_AGRICCOMERCIO.ID LEFT OUTER JOIN TAB_APOIO_UNIDMED_TAMANHO ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_AGRICUNIT = TAB_APOIO_UNIDMED_TAMANHO.ID LEFT OUTER JOIN TAB_APOIO_FREQCONSUMPROT ON TAB_FISH_COOP_ENTREVISTA.FISH_COOP_CONSUMOPEIXE = TAB_APOIO_FREQCONSUMPROT.ID LEFT OUTER JOIN TAB_FISH_COOP_CARACTERIZACAO ON TAB_FISH_COOP_CARACTERIZACAO.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_FISH_COOP_EXPECTATIVAS ON TAB_FISH_COOP_EXPECTATIVAS.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_CARACT_PESCANDO ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_PESCANDO = TAB_APOIO_BOOLEANO_CARACT_PESCANDO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_CARACT_SOZINHO ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_SOZINHO = TAB_APOIO_BOOLEANO_CARACT_SOZINHO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_CARACT_ORNAMENTAL ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_ORNAMENTAL = TAB_APOIO_BOOLEANO_CARACT_ORNAMENTAL.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_CARACT_CONSUMO ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_CONSUMO = TAB_APOIO_BOOLEANO_CARACT_CONSUMO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_CANOA_PROP ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_CANOA_PROP = TAB_APOIO_BOOLEANO_CANOA_PROP.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_BARCO_PROP ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_BARCO_PROP = TAB_APOIO_BOOLEANO_BARCO_PROP.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_BARCO_ALUG ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_BARCO_ALUG = TAB_APOIO_BOOLEANO_BARCO_ALUG.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_MOTOR_PROP ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_MOTOR_PROP = TAB_APOIO_BOOLEANO_MOTOR_PROP.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_MOTOR_ALUG ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_MOTOR_ALUG = TAB_APOIO_BOOLEANO_MOTOR_ALUG.ID LEFT OUTER JOIN TAB_APOIO_PESCA_TIPO ON TAB_FISH_COOP_CARACTERIZACAO.FISH_COOCAR_DESTINO = TAB_APOIO_PESCA_TIPO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_EXPEC_PART ON TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_PART = TAB_APOIO_BOOLEANO_EXPEC_PART.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_EXPEC_FILIACAO ON TAB_FISH_COOP_EXPECTATIVAS.FISH_COOEXP_FILIACAO = TAB_APOIO_BOOLEANO_EXPEC_FILIACAO.ID WHERE TAB_FISH_FAMILIAS.FISH_FAM_STT_COOP = 1 ORDER BY TAB_FISH_COOP_ENTREVISTA.FISH_COOP_DTENTREVISTA ASC, TAB_FISH_COOP_ENTREVISTA.FISH_COOP_QUEST ASC;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ID'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CHEFE_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CONJ_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_OFIC_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_EMER_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_PORT_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_BAIRRO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_MUNIC_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_USO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOCAL_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_MUNIC_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_USO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_LINK_STATUS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_LINK_BENEFICIO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_QUEST'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_COOP_DTENTREVISTA'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_LOCENTREVISTA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_ATIVPRINCIPAL_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_ATIVSECUNDARIA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_COUNT_PESSOAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_COUNT_PESCADORES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_ATIVPESCA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_ATIVPESCATEMPO'].' '.$vetor['FISH_COOP_ATIVPESCAUNIT_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_ATIVPESCATIPO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_PROJETONESA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_OUTRASRENDAS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_BENEFSOCIAIS_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_AGRICULTURA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_AGRICCOMERCIO_DESC'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_COOP_AGRICAREA'],2,',','.').' '.$vetor['FISH_COOP_AGRICUNIT_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_AGRICPESSOAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_AGRICDESCRICAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_CONSUMOPEIXE_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOP_OBSERVACOES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_PESCANDO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_MOTIVO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_SOZINHO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_QTS_PESSOAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_QTS_FAMILIA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_ORNAMENTAL_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_CONSUMO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_DESTINO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_DIAS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_VEZES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_KG_FORADEFESO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_KG_DENTRODEFESO'].'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_COOCAR_DESP_COMBS'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_COOCAR_DESP_GELO'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_COOCAR_DESP_RANCHO'],2,',','.').'</td>';
				$tabela .= '<td>'.number_format($vetor['FISH_COOCAR_DESP_OUTROS'],2,',','.').'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_CANOA_PROP_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_CANOA_PROP_QTS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_BARCO_PROP_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_BARCO_PROP_QTS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_BARCO_ALUG_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_BARCO_ALUG_QTS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_MOTOR_PROP_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_MOTOR_PROP_QTS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_MOTOR_ALUG_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOCAR_MOTOR_ALUG_QTS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_PART_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_PART_QUAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_DIFICULDADES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_CONTRIBUICAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_FILIACAO_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_FILI_SIM'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_FILI_NAO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_COOEXP_PERCEPCAO'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_fish_coop_completo.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>