<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Código</b></th>';
			$tabela .= '<th align="center"><b>Caso Emergencial?</b></th>';
			$tabela .= '<th align="center"><b>Usuário do Porto?</b></th>';
			$tabela .= '<th align="center"><b>Participante das Oficinas?</b></th>';
			$tabela .= '<th align="center"><b>Nome do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Apelido</b></th>';
			$tabela .= '<th align="center"><b>Nome do Cônjuge</b></th>';
			$tabela .= '<th align="center"><b>Apelido</b></th>';
			$tabela .= '<th align="center"><b>Data do Registro</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Urbano?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Urbano</b></th>';
			$tabela .= '<th align="center"><b>Complemento/Referência</b></th>';
			$tabela .= '<th align="center"><b>Bairro</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Rural?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Rural</b></th>';
			$tabela .= '<th align="center"><b>Complemento/Referência</b></th>';
			$tabela .= '<th align="center"><b>Localidade</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Telefone(s)</b></th>';
			$tabela .= '<th align="center"><b>Coord. UTM E</b></th>';
			$tabela .= '<th align="center"><b>Coord. UTM N</b></th>';
			$tabela .= '<th align="center"><b>Fuso da Coordenada UTM</b></th>';
			$tabela .= '<th align="center"><b>Possuí Cadastro ATES/Rep. Rural/RIR?</b></th>';
			$tabela .= '<th align="center"><b>Situação Emergêncial?</b></th>';
			$tabela .= '<th align="center"><b>Declara-se Vulnerável?</b></th>';
			$tabela .= '<th align="center"><b>Relato da Situação da Família</b></th>';
			$tabela .= '<th align="center"><b>Barco - Novo?</b></th>';
			$tabela .= '<th align="center"><b>Barco - Reparos?</b></th>';
			$tabela .= '<th align="center"><b>Relato da Situação do Barco</b></th>';
			$tabela .= '<th align="center"><b>Visita Realizada?</b></th>';
			$tabela .= '<th align="center"><b>Data da Visita</b></th>';
			$tabela .= '<th align="center"><b>Questionário Aplicado?</b></th>';
			$tabela .= '<th align="center"><b>Data da Aplicação do Questionário</b></th>';
			$tabela .= '<th align="center"><b>Número Questionário</b></th>';
			$tabela .= '<th align="center"><b>Pesquisador</b></th>';
			$tabela .= '<th align="center"><b>Formulário Tabulado?</b></th>';
			$tabela .= '<th align="center"><b>Data da Tabulação</b></th>';
			$tabela .= '<th align="center"><b>Relatório Concluído?</b></th>';
			$tabela .= '<th align="center"><b>Data do Relatório</b></th>';
			$tabela .= '<th align="center"><b>Número de tentativas de Visita</b></th>';
			$tabela .= '<th align="center"><b>Número de tentativas por Telefone</b></th>';
			$tabela .= '<th align="center"><b>Observações das Visitas/Entrevista</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Nova Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Novo Motor?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Reparo na Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Tralhas?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Rancho/Cesta Básica?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Projeto de Ger. de Renda?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Qual Projeto?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Atendimento Social?</b></th>';
			$tabela .= '<th align="center"><b>Solicita - Demais Solicitações?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Cooperativa?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Nova Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Reparo na Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Novo Motor?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralhas?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tipo da Tralha</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralha Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Data da Entrega</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho/Cesta Básica?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Qtde Entregas</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Primeira Entrega?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Segunda Entrega?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Terceira Entrega?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Quarta Entrega?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho - Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Projeto de Ger. de Renda?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Qual Projeto?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Atendimento Social?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Demais Encaminhamentos?</b></th>';
			$tabela .= '<th align="center"><b>Plano de Atendimento - Relato</b></th>';
			$tabela .= '<th align="center"><b>Plano de Atendimento - Encaminhamentos</b></th>';
			$tabela .= '<th align="center"><b>Plano de Atendimento - Resumo</b></th>';
			$tabela .= '<th align="center"><b>Plano de Atendimento - Encaminhamentos - NE</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Realizada??</b></th>';
			$tabela .= '<th align="center"><b>Data da Devolutiva</b></th>';
			$tabela .= '<th align="center"><b>Devolutiva Aceita?</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_FISH_FAMILIAS.FISH_FAM_ID AS FAMILIA_ID, BOOLEANO_STT_EMER.DESCRICAO AS FAMILIA_STT_EMER, BOOLEANO_STT_PORT.DESCRICAO AS FAMILIA_STT_PORT, BOOLEANO_STT_OFIC.DESCRICAO AS FAMILIA_STT_OFIC, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_NOME AS FAMILIA_CHEFE_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_APELIDO AS FAMILIA_CHEFE_APELIDO, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_NOME AS FAMILIA_CONJ_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_APELIDO AS FAMILIA_CONJ_APELIDO, TAB_FISH_FAMILIAS.FISH_FAM_DTREGISTRO AS FAMILIA_DT_REGISTRO, BOOLEANO_URB.DESCRICAO AS FAMILIA_ENDURB, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_LOGR AS FAMILIA_ENDURB_LOGR, TAB_APOIO_BAIRROS.DESCRICAO AS FAMILIA_ENDURB_LOCAL, MUNICIPIO_URB.DESCRICAO AS FAMILIA_ENDURB_MUNIC, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_COMPL AS FAMILIA_ENDURB_COMPL, BOOLEANO_RUR.DESCRICAO AS FAMILIA_ENDRUR, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOGR AS FAMILIA_ENDRUR_LOGR, TAB_APOIO_LOCALIDADES.DESCRICAO AS FAMILIA_ENDRUR_LOCAL, MUNICIPIO_RUR.DESCRICAO AS FAMILIA_ENDRUR_MUNIC, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_COMPL AS FAMILIA_ENDRUR_COMPL, TAB_FISH_FAMILIAS.FISH_FAM_TELEFONES AS FAMILIA_TELEFONES, TAB_FISH_FAMILIAS.FISH_FAM_UTME AS FAMILIA_UTME, TAB_FISH_FAMILIAS.FISH_FAM_UTMN AS FAMILIA_UTMN, TAB_APOIO_FUSOS.DESCRICAO AS FAMILIA_FUSO, BOOLEANO_CADASTRO.DESCRICAO AS FAMILIA_LINK_STATUS, TAB_FISH_FAMILIAS.FISH_FAM_LINK_CODIGO AS FAMILIA_LINK_CODIGO, BOOLEANO_DADOS_EMERG.DESCRICAO AS FAMILIA_DADOS_EMERG, BOOLEANO_DADOS_VULNERAVEL.DESCRICAO AS FAMILIA_DADOS_VULNERAVEL, BOOLEANO_DADOS_BARCO_NOVO.DESCRICAO AS FAMILIA_DADOS_BARCO_NOVO, BOOLEANO_DADOS_BARCO_REPARO.DESCRICAO AS FAMILIA_DADOS_BARCO_REPARO, TAB_FISH_DADOS.FISH_DADOS_SINTESE AS FAMILIA_DADOS_SINTESE, TAB_FISH_DADOS.FISH_DADOS_EMBARCACAO AS FAMILIA_DADOS_EMBARCACAO, BOOLEANO_PERFILENT_VISITA.DESCRICAO AS FAMILIA_PERFILENT_VISITA, TAB_FISH_PERFILENT.FISH_PERFIL_DTVISITA AS FAMILIA_PERFILENT_DTVISITA, BOOLEANO_PERFILENT_APLIC.DESCRICAO AS FAMILIA_PERFILENT_APLIC, TAB_FISH_PERFILENT.FISH_PERFIL_DTAPLIC AS FAMILIA_PERFILENT_DTAPLIC, TAB_FISH_PERFILENT.FISH_PERFIL_PESQUISADOR AS FAMILIA_PERFILENT_PESQUISADOR, TAB_FISH_PERFILENT.FISH_PERFIL_QUEST AS FAMILIA_PERFILENT_QUEST, BOOLEANO_PERFILENT_TAB.DESCRICAO AS FAMILIA_PERFILENT_TAB, TAB_FISH_PERFILENT.FISH_PERFIL_DTTAB AS FAMILIA_PERFILENT_DTTAB, BOOLEANO_PERFILENT_RELAT.DESCRICAO AS FAMILIA_PERFILENT_RELAT, TAB_FISH_PERFILENT.FISH_PERFIL_DTRELAT AS FAMILIA_PERFILENT_DTRELAT, BOOLEANO_PEDIDO_BARCO.DESCRICAO AS FAMILIA_PERFILENT_P_BARCO, BOOLEANO_PEDIDO_MOTOR.DESCRICAO AS FAMILIA_PERFILENT_P_MOTOR, BOOLEANO_PEDIDO_REPAROS.DESCRICAO AS FAMILIA_PERFILENT_P_REPAROS, BOOLEANO_PEDIDO_TRALHA.DESCRICAO AS FAMILIA_PERFILENT_P_TRALHA, BOOLEANO_PEDIDO_CESTA.DESCRICAO AS FAMILIA_PERFILENT_P_CESTA, BOOLEANO_PEDIDO_RENDA.DESCRICAO AS FAMILIA_PERFILENT_P_RENDA, BOOLEANO_PEDIDO_ATEND.DESCRICAO AS FAMILIA_PERFILENT_P_ATEND, BOOLEANO_ENCAM_COOP.DESCRICAO AS FAMILIA_PERFILENT_E_COOP, BOOLEANO_ENCAM_BARCO.DESCRICAO AS FAMILIA_PERFILENT_E_BARCO, BOOLEANO_ENCAM_BARCO_ENT.DESCRICAO AS FAMILIA_PERFILENT_E_BARCO_ENT,  TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENTDT AS FAMILIA_PERFILENT_E_BARCO_ENTDT, BOOLEANO_ENCAM_MOTOR.DESCRICAO AS FAMILIA_PERFILENT_E_MOTOR, BOOLEANO_ENCAM_MOTOR_ENT.DESCRICAO AS FAMILIA_PERFILENT_E_MOTOR_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENTDT AS FAMILIA_PERFILENT_E_MOTOR_ENTDT, BOOLEANO_ENCAM_REPAROS.DESCRICAO AS FAMILIA_PERFILENT_E_REPAROS, BOOLEANO_ENCAM_TRALHA.DESCRICAO AS FAMILIA_PERFILENT_E_TRALHA, BOOLEANO_ENCAM_TRALHA_ENT.DESCRICAO AS FAMILIA_PERFILENT_E_TRALHA_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENTDT AS FAMILIA_PERFILENT_E_TRALHA_ENTDT, BOOLEANO_ENCAM_CESTA.DESCRICAO AS FAMILIA_PERFILENT_E_CESTA, BOOLEANO_ENCAM_CESTA_ENT01.DESCRICAO AS FAMILIA_PERFILENT_E_CESTA_ENT01, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01DT AS FAMILIA_PERFILENT_E_CESTA_ENT01DT, BOOLEANO_ENCAM_CESTA_ENT02.DESCRICAO AS FAMILIA_PERFILENT_E_CESTA_ENT02, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02DT AS FAMILIA_PERFILENT_E_CESTA_ENT02DT, BOOLEANO_ENCAM_CESTA_ENT03.DESCRICAO AS FAMILIA_PERFILENT_E_CESTA_ENT03, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03DT AS FAMILIA_PERFILENT_E_CESTA_ENT03DT, BOOLEANO_ENCAM_CESTA_ENT04.DESCRICAO AS FAMILIA_PERFILENT_E_CESTA_ENT04, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04DT AS FAMILIA_PERFILENT_E_CESTA_ENT04DT, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENTQT AS FAMILIA_PERFILENT_E_CESTA_ENTREGA_QT, BOOLEANO_ENCAM_RENDA.DESCRICAO AS FAMILIA_PERFILENT_E_RENDA, BOOLEANO_ENCAM_ATEND.DESCRICAO AS FAMILIA_PERFILENT_E_ATEND, PROJETO_PEDIDO_PROJETO.DESCRICAO AS FAMILIA_PERFILENT_P_PROJ, PROJETO_ENCAM_PROJETO.DESCRICAO AS FAMILIA_PERFILENT_E_PROJ, TAB_FISH_PERFILENT.FISH_PERFIL_P_OUTROS AS FAMILIA_PERFILENT_P_OUTROS, TAB_FISH_PERFILENT.FISH_PERFIL_E_OUTROS AS FAMILIA_PERFILENT_E_OUTROS, BOOLEANO_DEVOLUT.DESCRICAO AS FAMILIA_PERFILENT_DEVOLUT, TAB_FISH_PERFILENT.FISH_PERFIL_DTDEVOLUT AS FAMILIA_PERFILENT_DTDEVOLUT, BOOLEANO_DEVOLUT_ACEITE.DESCRICAO AS FAMILIA_PERFILENT_DEVOLUT_ACEITE, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_RELATO AS FAMILIA_PERFILENT_ATEND_RELATO, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_ATEND AS FAMILIA_PERFILENT_ATEND_ATEND, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_RESUMO AS FAMILIA_PERFILENT_ATEND_RESUMO, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_ENCAM AS FAMILIA_PERFILENT_ATEND_ENCAM, TAB_APOIO_TRALHA.DESCRICAO AS FAMILIA_PERFILENT_E_TRALHA_TP FROM TAB_FISH_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_URB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB = BOOLEANO_URB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_RUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR = BOOLEANO_RUR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_STT_EMER ON TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = BOOLEANO_STT_EMER.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_STT_PORT ON TAB_FISH_FAMILIAS.FISH_FAM_STT_PORT = BOOLEANO_STT_PORT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_STT_OFIC ON TAB_FISH_FAMILIAS.FISH_FAM_STT_OFIC = BOOLEANO_STT_OFIC.ID LEFT OUTER JOIN TAB_APOIO_BAIRROS ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_BAIRRO = TAB_APOIO_BAIRROS.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS MUNICIPIO_URB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_MUNIC = MUNICIPIO_URB.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS MUNICIPIO_RUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_MUNIC = MUNICIPIO_RUR.ID LEFT OUTER JOIN TAB_APOIO_LOCALIDADES ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOCAL = TAB_APOIO_LOCALIDADES.ID LEFT OUTER JOIN TAB_APOIO_FUSOS ON TAB_FISH_FAMILIAS.FISH_FAM_FUSO = TAB_APOIO_FUSOS.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_CADASTRO ON TAB_FISH_FAMILIAS.FISH_FAM_LINK_STATUS = BOOLEANO_CADASTRO.ID LEFT OUTER JOIN TAB_FISH_DADOS ON TAB_FISH_DADOS.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_FISH_PERFILENT ON TAB_FISH_PERFILENT.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DADOS_EMERG ON TAB_FISH_DADOS.FISH_DADOS_EMERG = BOOLEANO_DADOS_EMERG.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DADOS_VULNERAVEL ON TAB_FISH_DADOS.FISH_DADOS_VULNERAVEL = BOOLEANO_DADOS_VULNERAVEL.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DADOS_BARCO_NOVO ON TAB_FISH_DADOS.FISH_DADOS_BARCO_NOVO = BOOLEANO_DADOS_BARCO_NOVO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DADOS_BARCO_REPARO ON TAB_FISH_DADOS.FISH_DADOS_BARCO_REPARO = BOOLEANO_DADOS_BARCO_REPARO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PERFILENT_VISITA ON TAB_FISH_PERFILENT.FISH_PERFIL_VISITA = BOOLEANO_PERFILENT_VISITA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PERFILENT_APLIC ON TAB_FISH_PERFILENT.FISH_PERFIL_APLIC = BOOLEANO_PERFILENT_APLIC.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PERFILENT_TAB ON TAB_FISH_PERFILENT.FISH_PERFIL_TAB = BOOLEANO_PERFILENT_TAB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PERFILENT_RELAT ON TAB_FISH_PERFILENT.FISH_PERFIL_RELAT = BOOLEANO_PERFILENT_RELAT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_BARCO ON TAB_FISH_PERFILENT.FISH_PERFIL_P_BARCO = BOOLEANO_PEDIDO_BARCO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_MOTOR ON TAB_FISH_PERFILENT.FISH_PERFIL_P_MOTOR = BOOLEANO_PEDIDO_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_REPAROS ON TAB_FISH_PERFILENT.FISH_PERFIL_P_REPAROS = BOOLEANO_PEDIDO_REPAROS.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_P_TRALHA = BOOLEANO_PEDIDO_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_CESTA ON TAB_FISH_PERFILENT.FISH_PERFIL_P_CESTA = BOOLEANO_PEDIDO_CESTA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_RENDA ON TAB_FISH_PERFILENT.FISH_PERFIL_P_RENDA = BOOLEANO_PEDIDO_RENDA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_PEDIDO_ATEND ON TAB_FISH_PERFILENT.FISH_PERFIL_P_ATEND = BOOLEANO_PEDIDO_ATEND.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_COOP ON TAB_FISH_PERFILENT.FISH_PERFIL_E_COOP = BOOLEANO_ENCAM_COOP.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_BARCO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO = BOOLEANO_ENCAM_BARCO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_BARCO_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENT = BOOLEANO_ENCAM_BARCO_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_MOTOR ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR = BOOLEANO_ENCAM_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_MOTOR_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENT = BOOLEANO_ENCAM_MOTOR_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_REPAROS ON TAB_FISH_PERFILENT.FISH_PERFIL_E_REPAROS = BOOLEANO_ENCAM_REPAROS.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA = BOOLEANO_ENCAM_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_TRALHA_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENT = BOOLEANO_ENCAM_TRALHA_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_CESTA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA = BOOLEANO_ENCAM_CESTA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_CESTA_ENT01 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01 = BOOLEANO_ENCAM_CESTA_ENT01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_CESTA_ENT02 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02 = BOOLEANO_ENCAM_CESTA_ENT02.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_CESTA_ENT03 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03 = BOOLEANO_ENCAM_CESTA_ENT03.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_CESTA_ENT04 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04 = BOOLEANO_ENCAM_CESTA_ENT04.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_RENDA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_RENDA = BOOLEANO_ENCAM_RENDA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_ENCAM_ATEND ON TAB_FISH_PERFILENT.FISH_PERFIL_E_ATEND = BOOLEANO_ENCAM_ATEND.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DEVOLUT ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT = BOOLEANO_DEVOLUT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS BOOLEANO_DEVOLUT_ACEITE ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT_ACEITE = BOOLEANO_DEVOLUT_ACEITE.ID LEFT OUTER JOIN TAB_APOIO_TPPROJETO AS PROJETO_PEDIDO_PROJETO ON TAB_FISH_PERFILENT.FISH_PERFIL_P_PROJ = PROJETO_PEDIDO_PROJETO.ID LEFT OUTER JOIN TAB_APOIO_TPPROJETO AS PROJETO_ENCAM_PROJETO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_PROJ = PROJETO_ENCAM_PROJETO.ID LEFT OUTER JOIN TAB_APOIO_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_TP = TAB_APOIO_TRALHA.ID ORDER BY FAMILIA_ID ASC;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FAMILIA_ID'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_STT_EMER'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_STT_PORT'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_STT_OFIC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_CHEFE_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_CHEFE_APELIDO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_CONJ_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_CONJ_APELIDO'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_DT_REGISTRO'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDURB'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDURB_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDURB_COMPL'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDURB_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDURB_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDRUR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDRUR_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDRUR_COMPL'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDRUR_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_ENDRUR_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_UTME'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_UTMN'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_FUSO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_LINK_STATUS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_EMERG'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_VULNERAVEL'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_SINTESE'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_BARCO_NOVO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_BARCO_REPARO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_DADOS_EMBARCACAO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_VISITA'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_DTVISITA'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_APLIC'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_DTAPLIC'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_QUEST'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_PESQUISADOR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_TAB'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_DTTAB'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_RELAT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_DTRELAT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_VLOCO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_VFONE'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_OBS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_BARCO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_MOTOR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_REPAROS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_TRALHA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_CESTA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_RENDA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_PROJ'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_ATEND'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_P_OUTROS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_COOP'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_BARCO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_BARCO_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_BARCO_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_REPAROS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_MOTOR'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_MOTOR_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_MOTOR_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_TRALHA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_TRALHA_TP'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_TRALHA_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_TRALHA_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA_ENTREGA_QT'].'</td>';

				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA_ENT01'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_CESTA_ENT01DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA_ENT02'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_CESTA_ENT02DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA_ENT03'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_CESTA_ENT03DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_CESTA_ENT04'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_E_CESTA_ENT04DT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_RENDA'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_PROJ'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_ATEND'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_E_OUTROS'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_ATEND_RELATO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_ATEND_ATEND'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_ATEND_RESUMO'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_ATEND_ENCAM'].'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_DEVOLUT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FAMILIA_PERFILENT_DTDEVOLUT'])).'</td>';
				$tabela .= '<td>'.$vetor['FAMILIA_PERFILENT_DEVOLUT_ACEITE'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_fish_familias.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>