<?php
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			$tabela = '<table border=1>';
			$tabela .= '<thead>';
			$tabela .= '<tr>';
			$tabela .= '<th align="center"><b>Número Questionário</b></th>';
			$tabela .= '<th align="center"><b>Usuário do Porto?</b></th>';
			$tabela .= '<th align="center"><b>Nome do Chefe da Família</b></th>';
			$tabela .= '<th align="center"><b>Nome do Cônjuge</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Urbano?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Urbano</b></th>';
			$tabela .= '<th align="center"><b>Bairro</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Possuí Endereço Rural?</b></th>';
			$tabela .= '<th align="center"><b>Endereço Rural</b></th>';
			$tabela .= '<th align="center"><b>Localidade</b></th>';
			$tabela .= '<th align="center"><b>Município</b></th>';
			$tabela .= '<th align="center"><b>Telefone(s)</b></th>';
			$tabela .= '<th align="center"><b>ATES/Rep. Rural?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Embarcação Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Motor Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralhas?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralha Entregue?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralha Data</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Tralha Conteúdo</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho?</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - Rancho Qtde</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - 1º Rancho</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - 2º Rancho</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - 3º Rancho</b></th>';
			$tabela .= '<th align="center"><b>Encaminhamentos - 4º Rancho</b></th>';
			$tabela .= '<th align="center"><b>Eventos - Data</b></th>';
			$tabela .= '<th align="center"><b>Eventos - Tipo</b></th>';
			$tabela .= '<th align="center"><b>Eventos - Resumo</b></th>';
			$tabela .= '<th align="center"><b>Eventos - Técnico(s)</b></th>';
			$tabela .= '<th align="center"><b>Embarcação Vistoriada?</b></th>';
			$tabela .= '<th align="center"><b>Motor Vistoriado?</b></th>';
			$tabela .= '<th align="center"><b>Tralha Vistoriada?</b></th>';
			$tabela .= '<th align="center"><b>Situação do Material</b></th>';
			$tabela .= '<th align="center"><b>Relato da Visita</b></th>';
			$tabela .= '<th align="center"><b>Percepção do Entrevistado</b></th>';
			$tabela .= '<th align="center"><b>Percepção do Entrevistador</b></th>';
			$tabela .= '<th align="center"><b>Outras Informações</b></th>';
			$tabela .= '</tr>';
			$tabela .= '</thead>';
			$tabela .= '<tbody>';
			$sql = mysql_query("SELECT TAB_FISH_FAMILIAS.FISH_FAM_ID, TAB_FISH_PERFILENT.FISH_PERFIL_QUEST, TAB_FISH_PERFILENT.FISH_PERFIL_PESQUISADOR, TAB_APOIO_BOOLEANO_STT_EMERG.DESCRICAO AS FISH_FAM_STT_EMERG, TAB_APOIO_BOOLEANO_STT_PORTO.DESCRICAO AS FISH_FAM_STT_PORTO, TAB_FISH_FAMILIAS.FISH_FAM_CHEFE_NOME, TAB_FISH_FAMILIAS.FISH_FAM_CONJ_NOME, TAB_APOIO_BOOLEANO_ENDURB.DESCRICAO AS FISH_FAM_ENDURB, TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_LOGR, TAB_APOIO_BAIRROS.DESCRICAO AS FISH_FAM_ENDURB_LOCAL, TAB_APOIO_MUNICIPIOS_URB.DESCRICAO AS  FISH_FAM_ENDURB_MUNIC, TAB_APOIO_BOOLEANO_ENDRUR.DESCRICAO AS FISH_FAM_ENDRUR, TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOGR, TAB_APOIO_LOCALIDADES.DESCRICAO AS FISH_FAM_ENDRUR_LOCAL, TAB_APOIO_MUNICIPIOS_RUR.DESCRICAO AS FISH_FAM_ENDRUR_MUNIC, TAB_FISH_FAMILIAS.FISH_FAM_TELEFONES, TAB_APOIO_BOOLEANO_415421.DESCRICAO AS FISH_FAM_ATES, TAB_APOIO_BENEFICIOS.DESCRICAO AS FISH_FAM_ATES_BENEF, TAB_APOIO_BOOLEANO_E_BARCO.DESCRICAO AS FISH_PERFIL_E_BARCO, TAB_APOIO_BOOLEANO_E_BARCO_ENT.DESCRICAO AS FISH_PERFIL_E_BARCO_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENTDT, TAB_APOIO_BOOLEANO_E_MOTOR.DESCRICAO AS FISH_PERFIL_E_MOTOR, TAB_APOIO_BOOLEANO_E_MOTOR_ENT.DESCRICAO AS FISH_PERFIL_E_MOTOR_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENTDT, TAB_APOIO_BOOLEANO_E_TRALHA.DESCRICAO AS FISH_PERFIL_E_TRALHA, TAB_APOIO_BOOLEANO_E_TRALHA_ENT.DESCRICAO AS FISH_PERFIL_E_TRALHA_ENT, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENTDT, TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_DESC, TAB_APOIO_BOOLEANO_E_RANCHO.DESCRICAO AS FISH_PERFIL_E_RANCHO, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENTQT AS FISH_PERFIL_E_RANCHO_QT, TAB_APOIO_BOOLEANO_E_RANCHO01.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT01, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01DT AS FISH_PERFIL_E_RANCHO_ENT01DT, TAB_APOIO_BOOLEANO_E_RANCHO02.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT02, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02DT AS FISH_PERFIL_E_RANCHO_ENT02DT, TAB_APOIO_BOOLEANO_E_RANCHO03.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT03, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03DT AS FISH_PERFIL_E_RANCHO_ENT03DT, TAB_APOIO_BOOLEANO_E_RANCHO04.DESCRICAO AS FISH_PERFIL_E_RANCHO_ENT04, TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04DT AS FISH_PERFIL_E_RANCHO_ENT04DT, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_RELATO, TAB_FISH_PERFILENT.FISH_PERFIL_TRAN_ATEND, TAB_APOIO_BOOLEANO_DEVOL.DESCRICAO AS FISH_PERFIL_DEVOLUT, TAB_FISH_PERFILENT.FISH_PERFIL_DTDEVOLUT AS FISH_PERFIL_DEVOLUT_DT, TAB_APOIO_BOOLEANO_DEVOL_OK.DESCRICAO AS FISH_PERFIL_DEVOLUT_ACEITE, TAB_FISH_EVENTOS.FISH_EVE_CODIGO, TAB_FISH_EVENTOS.FISH_EVE_DATA, TAB_APOIO_EVENTOS.DESCRICAO AS FISH_EVE_TIPO, TAB_FISH_EVENTOS.FISH_EVE_OBSERVACOES, VIEW_FISH_EVE_TECNICOS.FISH_EVE_TECNICOS, VIEW_FISH_ACOMP_VIST_EMB.FISH_CLASS_DESCRICAO AS FISH_ACOMP_VIST_EMB, VIEW_FISH_ACOMP_VIST_MOT.FISH_CLASS_DESCRICAO AS FISH_ACOMP_VIST_MOT, VIEW_FISH_ACOMP_VIST_TRA.FISH_CLASS_DESCRICAO AS FISH_ACOMP_VIST_TRA, VIEW_FISH_ACOMP_SITTRA.FISH_CLASS_DESCRICAO AS FISH_ACOMP_SITTRA, VIEW_FISH_ACOMP_RELATO.FISH_CLASS_DESCRICAO AS FISH_ACOMP_RELATO, VIEW_FISH_ACOMP_PERC_PESC.FISH_CLASS_DESCRICAO AS FISH_ACOMP_PERC_PESC, VIEW_FISH_ACOMP_PERC_TEC.FISH_CLASS_DESCRICAO AS FISH_ACOMP_PERC_TEC, VIEW_FISH_ACOMP_OUTROS.FISH_CLASS_DESCRICAO AS FISH_ACOMP_OUTROS FROM TAB_FISH_FAMILIAS LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_PORTO ON TAB_FISH_FAMILIAS.FISH_FAM_STT_PORT = TAB_APOIO_BOOLEANO_STT_PORTO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_STT_EMERG ON TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = TAB_APOIO_BOOLEANO_STT_EMERG.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDURB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB = TAB_APOIO_BOOLEANO_ENDURB.ID LEFT OUTER JOIN TAB_APOIO_BAIRROS ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_BAIRRO = TAB_APOIO_BAIRROS.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_URB ON TAB_FISH_FAMILIAS.FISH_FAM_ENDURB_MUNIC = TAB_APOIO_MUNICIPIOS_URB.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_ENDRUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR = TAB_APOIO_BOOLEANO_ENDRUR.ID LEFT OUTER JOIN TAB_APOIO_LOCALIDADES ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_LOCAL = TAB_APOIO_LOCALIDADES.ID LEFT OUTER JOIN TAB_APOIO_MUNICIPIOS AS TAB_APOIO_MUNICIPIOS_RUR ON TAB_FISH_FAMILIAS.FISH_FAM_ENDRUR_MUNIC = TAB_APOIO_MUNICIPIOS_RUR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_415421 ON TAB_FISH_FAMILIAS.FISH_FAM_LINK_STATUS = TAB_APOIO_BOOLEANO_415421.ID LEFT OUTER JOIN TAB_FISH_PERFILENT ON TAB_FISH_PERFILENT.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO = TAB_APOIO_BOOLEANO_E_BARCO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_BARCO_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_BARCO_ENT = TAB_APOIO_BOOLEANO_E_BARCO_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR = TAB_APOIO_BOOLEANO_E_MOTOR.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_MOTOR_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_MOTOR_ENT = TAB_APOIO_BOOLEANO_E_MOTOR_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA = TAB_APOIO_BOOLEANO_E_TRALHA.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_TRALHA_ENT ON TAB_FISH_PERFILENT.FISH_PERFIL_E_TRALHA_ENT = TAB_APOIO_BOOLEANO_E_TRALHA_ENT.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA = TAB_APOIO_BOOLEANO_E_RANCHO.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO01 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT01 = TAB_APOIO_BOOLEANO_E_RANCHO01.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO02 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT02 = TAB_APOIO_BOOLEANO_E_RANCHO02.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO03 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT03 = TAB_APOIO_BOOLEANO_E_RANCHO03.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_E_RANCHO04 ON TAB_FISH_PERFILENT.FISH_PERFIL_E_CESTA_ENT04 = TAB_APOIO_BOOLEANO_E_RANCHO04.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT = TAB_APOIO_BOOLEANO_DEVOL.ID LEFT OUTER JOIN TAB_APOIO_BOOLEANO AS TAB_APOIO_BOOLEANO_DEVOL_OK ON TAB_FISH_PERFILENT.FISH_PERFIL_DEVOLUT_ACEITE = TAB_APOIO_BOOLEANO_DEVOL_OK.ID LEFT OUTER JOIN TAB_FISH_EVENTOS ON TAB_FISH_EVENTOS.FISH_FAM_ID = TAB_FISH_FAMILIAS.FISH_FAM_ID LEFT OUTER JOIN TAB_APOIO_EVENTOS ON TAB_FISH_EVENTOS.FISH_EVE_TIPO = TAB_APOIO_EVENTOS.ID LEFT OUTER JOIN TAB_415421_FAMILIAS ON TAB_415421_FAMILIAS.FAMILIA_CODIGO = TAB_FISH_FAMILIAS.FISH_FAM_LINK_CODIGO LEFT OUTER JOIN TAB_APOIO_BENEFICIOS ON TAB_415421_FAMILIAS.FAMILIA_BENEFICIO = TAB_APOIO_BENEFICIOS.ID LEFT OUTER JOIN VIEW_FISH_EVE_TECNICOS ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_EVE_TECNICOS.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_VIST_EMB ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_VIST_EMB.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_VIST_MOT ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_VIST_MOT.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_VIST_TRA ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_VIST_TRA.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_SITTRA ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_SITTRA.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_RELATO ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_RELATO.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_PERC_PESC ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_PERC_PESC.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_PERC_TEC ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_PERC_TEC.FISH_EVE_CODIGO LEFT OUTER JOIN VIEW_FISH_ACOMP_OUTROS ON TAB_FISH_EVENTOS.FISH_EVE_CODIGO = VIEW_FISH_ACOMP_OUTROS.FISH_EVE_CODIGO WHERE TAB_FISH_FAMILIAS.FISH_FAM_STT_EMER = 1 AND TAB_FISH_EVENTOS.FISH_EVE_TIPO = 11 ORDER BY TAB_FISH_PERFILENT.FISH_PERFIL_QUEST ASC, TAB_FISH_EVENTOS.FISH_EVE_DATA ASC;", $db); 
			while ($vetor=mysql_fetch_array($sql)) {
				$tabela .= '<tr>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_QUEST'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_STT_PORTO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CHEFE_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_CONJ_NOME'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDURB_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOGR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_LOCAL'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ENDRUR_MUNIC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_TELEFONES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_FAM_ATES_BENEF'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_BARCO_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_BARCO_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_MOTOR_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_MOTOR_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_ENT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_TRALHA_ENTDT'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_TRALHA_DESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_PERFIL_E_RANCHO_QT'].'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT01DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT02DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT03DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_PERFIL_E_RANCHO_ENT04DT'])).'</td>';
				$tabela .= '<td>'.date('d/m/Y', strtotime($vetor['FISH_EVE_DATA'])).'</td>';
				$tabela .= '<td>'.$vetor['FISH_EVE_TIPO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_EVE_OBSERVACOES'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_EVE_TECNICOS'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_VIST_EMB'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_VIST_MOT'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_VIST_TRA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_SITTRA'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_RELATO'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_PERC_PESC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_PERC_TEC'].'</td>';
				$tabela .= '<td>'.$vetor['FISH_ACOMP_OUTROS'].'</td>';
				$tabela .= '</tr>';
			}
			$tabela .= '</tbody>';
			$tabela .= '</table>';
			header("Pragma: no-cache");
			header("Content-Type: application/msexcel; charset=utf-8");
			header("Content-Disposition: attachment; filename=excel_fish_1camp_acomp.xls");
			header("Content-Description: PHP Generated Data" );			
			header("Cache-Control: no-cache, must-revalidate");
			header("Content-type: application/force-download");  
			echo $tabela;
		}
	}
?>