<?php 
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("SELECT * FROM TAB_MAIN_USERS_PROJECTS WHERE ID_PROJETO = '$projeto' AND ID_USER = '$_SESSION[user]'", $db) or die(mysql_error());
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			function moeda($get_valor) { 
                $source = array('.', ',');  
                $replace = array('', '.'); 
                $valor = str_replace($source, $replace, $get_valor);
                return $valor;
			}
			
			$id_familia = $_GET['id_familia'];
			$FISH_COOCAR_ID = $_GET['FISH_COOCAR_ID'];
			
			$FISH_COOCAR_PESCANDO = $_POST['FISH_COOCAR_PESCANDO'];
			$FISH_COOCAR_MOTIVO = mb_convert_case($_POST['FISH_COOCAR_MOTIVO'], MB_CASE_UPPER, 'UTF-8');
			$FISH_COOCAR_SOZINHO = $_POST['FISH_COOCAR_SOZINHO'];
			$FISH_COOCAR_QTS_PESSOAS = $_POST['FISH_COOCAR_QTS_PESSOAS'];
			$FISH_COOCAR_QTS_FAMILIA = $_POST['FISH_COOCAR_QTS_FAMILIA'];
			$FISH_COOCAR_ORNAMENTAL = $_POST['FISH_COOCAR_ORNAMENTAL'];
			$FISH_COOCAR_CONSUMO = $_POST['FISH_COOCAR_CONSUMO'];
			$FISH_COOCAR_DESTINO = $_POST['FISH_COOCAR_DESTINO'];
			$FISH_COOCAR_DIAS = $_POST['FISH_COOCAR_DIAS'];
			$FISH_COOCAR_VEZES = $_POST['FISH_COOCAR_VEZES'];
			$FISH_COOCAR_KG_FORADEFESO = $_POST['FISH_COOCAR_KG_FORADEFESO'];
			$FISH_COOCAR_KG_DENTRODEFESO = $_POST['FISH_COOCAR_KG_DENTRODEFESO'];
			$FISH_COOCAR_DESP_COMBS = moeda($_POST['FISH_COOCAR_DESP_COMBS']);
			$FISH_COOCAR_DESP_GELO = moeda($_POST['FISH_COOCAR_DESP_GELO']);
			$FISH_COOCAR_DESP_RANCHO = moeda($_POST['FISH_COOCAR_DESP_RANCHO']);
			$FISH_COOCAR_DESP_OUTROS = moeda($_POST['FISH_COOCAR_DESP_OUTROS']);
			$FISH_COOCAR_CANOA_PROP = $_POST['FISH_COOCAR_CANOA_PROP'];
			$FISH_COOCAR_CANOA_PROP_QTS = $_POST['FISH_COOCAR_CANOA_PROP_QTS'];
			$FISH_COOCAR_BARCO_PROP = $_POST['FISH_COOCAR_BARCO_PROP'];
			$FISH_COOCAR_BARCO_PROP_QTS = $_POST['FISH_COOCAR_BARCO_PROP_QTS'];
			$FISH_COOCAR_BARCO_ALUG = $_POST['FISH_COOCAR_BARCO_ALUG'];
			$FISH_COOCAR_BARCO_ALUG_QTS = $_POST['FISH_COOCAR_BARCO_ALUG_QTS'];
			$FISH_COOCAR_MOTOR_PROP = $_POST['FISH_COOCAR_MOTOR_PROP'];
			$FISH_COOCAR_MOTOR_PROP_QTS = $_POST['FISH_COOCAR_MOTOR_PROP_QTS'];
			$FISH_COOCAR_MOTOR_ALUG = $_POST['FISH_COOCAR_MOTOR_ALUG'];
			$FISH_COOCAR_MOTOR_ALUG_QTS = $_POST['FISH_COOCAR_MOTOR_ALUG_QTS'];
			
			$comandoSql = "UPDATE TAB_FISH_COOP_CARACTERIZACAO SET FISH_COOCAR_PESCANDO = '$FISH_COOCAR_PESCANDO', FISH_COOCAR_MOTIVO = '$FISH_COOCAR_MOTIVO', FISH_COOCAR_SOZINHO = '$FISH_COOCAR_SOZINHO', FISH_COOCAR_QTS_PESSOAS = '$FISH_COOCAR_QTS_PESSOAS', FISH_COOCAR_QTS_FAMILIA = '$FISH_COOCAR_QTS_FAMILIA', FISH_COOCAR_ORNAMENTAL = '$FISH_COOCAR_ORNAMENTAL', FISH_COOCAR_CONSUMO = '$FISH_COOCAR_CONSUMO', FISH_COOCAR_DESTINO = '$FISH_COOCAR_DESTINO', FISH_COOCAR_DIAS = '$FISH_COOCAR_DIAS', FISH_COOCAR_VEZES = '$FISH_COOCAR_VEZES', FISH_COOCAR_KG_FORADEFESO = '$FISH_COOCAR_KG_FORADEFESO', FISH_COOCAR_KG_DENTRODEFESO = '$FISH_COOCAR_KG_DENTRODEFESO', FISH_COOCAR_DESP_COMBS = '$FISH_COOCAR_DESP_COMBS', FISH_COOCAR_DESP_GELO = '$FISH_COOCAR_DESP_GELO', FISH_COOCAR_DESP_RANCHO = '$FISH_COOCAR_DESP_RANCHO', FISH_COOCAR_DESP_OUTROS = '$FISH_COOCAR_DESP_OUTROS', FISH_COOCAR_CANOA_PROP = '$FISH_COOCAR_CANOA_PROP', FISH_COOCAR_CANOA_PROP_QTS = '$FISH_COOCAR_CANOA_PROP_QTS', FISH_COOCAR_BARCO_PROP = '$FISH_COOCAR_BARCO_PROP', FISH_COOCAR_BARCO_PROP_QTS = '$FISH_COOCAR_BARCO_PROP_QTS', FISH_COOCAR_BARCO_ALUG = '$FISH_COOCAR_BARCO_ALUG', FISH_COOCAR_BARCO_ALUG_QTS = '$FISH_COOCAR_BARCO_ALUG_QTS', FISH_COOCAR_MOTOR_PROP = '$FISH_COOCAR_MOTOR_PROP', FISH_COOCAR_MOTOR_PROP_QTS = '$FISH_COOCAR_MOTOR_PROP_QTS', FISH_COOCAR_MOTOR_ALUG = '$FISH_COOCAR_MOTOR_ALUG', FISH_COOCAR_MOTOR_ALUG_QTS = '$FISH_COOCAR_MOTOR_ALUG_QTS' WHERE FISH_COOCAR_ID = '$FISH_COOCAR_ID' AND FISH_FAM_ID = '$id_familia';";
//			echo $comandoSql.'<br/>';
			$sql = mysql_query($comandoSql, $db) or die(mysql_error());
			
			$vet_COOP_CARACT_MOTIVO = $_POST['FISH_CPCMOT_MOTIVO'];
			$cont_COOP_CARACT_MOTIVO = 0;
			foreach((array)$vet_COOP_CARACT_MOTIVO as $vet_COOP_CARACT_MOTIVOkey){
				$FISH_CPCMOT_MOTIVO = $_POST['FISH_CPCMOT_MOTIVO'][$cont_COOP_CARACT_MOTIVO];
				if(!$FISH_CPCMOT_MOTIVO == 0){
					$sql_consulta_COOP_CARACT_MOTIVO = mysql_query("SELECT FISH_CPCMOT_ID FROM TAB_FISH_COOCAR_MOTIVOS WHERE FISH_COOCAR_ID = '$FISH_COOCAR_ID' AND FISH_CPCMOT_MOTIVO = '$FISH_CPCMOT_MOTIVO';", $db) or die(mysql_error());
					$num_COOP_CARACT_MOTIVO = mysql_num_rows($sql_consulta_COOP_CARACT_MOTIVO);
					if($num_COOP_CARACT_MOTIVO == 0) {
						$sql_insert_COOP_CARACT_MOTIVO = mysql_query("INSERT INTO TAB_FISH_COOCAR_MOTIVOS (FISH_COOCAR_ID, FISH_CPCMOT_MOTIVO) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCMOT_MOTIVO');", $db) or die(mysql_error());
					}
				}
				$cont_COOP_CARACT_MOTIVO++;
			}

			$vet_COOP_CARACT_LOCAIS = $_POST['FISH_CPCLOC_LOCAL'];
			$cont_COOP_CARACT_LOCAIS = 0;
			foreach((array)$vet_COOP_CARACT_LOCAIS as $vet_COOP_CARACT_LOCAISkey){
				$FISH_CPCLOC_LOCAL = $_POST['FISH_CPCLOC_LOCAL'][$cont_COOP_CARACT_LOCAIS];
				if(!$FISH_CPCLOC_LOCAL == 0){
					$sql_consulta_COOP_CARACT_LOCAIS = mysql_query("SELECT FISH_CPCLOC_ID FROM TAB_FISH_COOCAR_LOCAIS WHERE FISH_COOCAR_ID = '$FISH_COOCAR_ID' AND FISH_CPCLOC_LOCAL = '$FISH_CPCLOC_LOCAL';", $db) or die(mysql_error());
					$num_COOP_CARACT_LOCAIS = mysql_num_rows($sql_consulta_COOP_CARACT_LOCAIS);
					if($num_COOP_CARACT_LOCAIS == 0) {
						$sql_insert_COOP_CARACT_LOCAIS = mysql_query("INSERT INTO TAB_FISH_COOCAR_LOCAIS (FISH_COOCAR_ID, FISH_CPCLOC_LOCAL) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCLOC_LOCAL');", $db) or die(mysql_error());
					}
				}
				$cont_COOP_CARACT_LOCAIS++;
			}

			$vet_COOP_CARACT_COMERCIO = $_POST['FISH_CPCCOM_COMERCIO'];
			$cont_COOP_CARACT_COMERCIO = 0;
			foreach((array)$vet_COOP_CARACT_COMERCIO as $vet_COOP_CARACT_COMERCIOkey){
				$FISH_CPCCOM_COMERCIO = $_POST['FISH_CPCCOM_COMERCIO'][$cont_COOP_CARACT_COMERCIO];
				if(!$FISH_CPCCOM_COMERCIO == 0){
					$sql_consulta_COOP_CARACT_COMERCIO = mysql_query("SELECT FISH_CPCCOM_ID FROM TAB_FISH_COOCAR_COMERCIO WHERE FISH_COOCAR_ID = '$FISH_COOCAR_ID' AND FISH_CPCCOM_COMERCIO = '$FISH_CPCCOM_COMERCIO';", $db) or die(mysql_error());
					$num_COOP_CARACT_COMERCIO = mysql_num_rows($sql_consulta_COOP_CARACT_COMERCIO);
					if($num_COOP_CARACT_COMERCIO == 0) {
						$sql_insert_COOP_CARACT_COMERCIO = mysql_query("INSERT INTO TAB_FISH_COOCAR_COMERCIO (FISH_COOCAR_ID, FISH_CPCCOM_COMERCIO) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCCOM_COMERCIO');", $db) or die(mysql_error());
					}
				}
				$cont_COOP_CARACT_COMERCIO++;
			}

			$vet_COOP_CARACT_ESPECIES = $_POST['FISH_CPCESP_ESPECIE'];
			$cont_COOP_CARACT_ESPECIES = 0;
			foreach((array)$vet_COOP_CARACT_ESPECIES as $vet_COOP_CARACT_ESPECIESkey){
				$FISH_CPCESP_ESPECIE = $_POST['FISH_CPCESP_ESPECIE'][$cont_COOP_CARACT_ESPECIES];
				$FISH_CPCESP_VALOR = moeda($_POST['FISH_CPCESP_VALOR'][$cont_COOP_CARACT_ESPECIES]);
				if(!$FISH_CPCESP_ESPECIE == 0){
					$sql_consulta_COOP_CARACT_ESPECIES = mysql_query("SELECT FISH_CPCESP_ID FROM TAB_FISH_COOCAR_ESPECIES WHERE FISH_COOCAR_ID = '$FISH_COOCAR_ID' AND FISH_CPCESP_ESPECIE = '$FISH_CPCESP_ESPECIE' AND FISH_CPCESP_VALOR = '$FISH_CPCESP_VALOR';", $db) or die(mysql_error());
					$num_COOP_CARACT_ESPECIES = mysql_num_rows($sql_consulta_COOP_CARACT_ESPECIES);
					if($num_COOP_CARACT_ESPECIES == 0) {
						$sql_insert_COOP_CARACT_ESPECIES = mysql_query("INSERT INTO TAB_FISH_COOCAR_ESPECIES (FISH_COOCAR_ID, FISH_CPCESP_ESPECIE, FISH_CPCESP_VALOR) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCESP_ESPECIE', '$FISH_CPCESP_VALOR');", $db) or die(mysql_error());
					}
				}
				$cont_COOP_CARACT_ESPECIES++;
			}

			$vet_COOP_CARACT_EMBARC = $_POST['FISH_CPCEMB_TIPO'];
			$cont_COOP_CARACT_EMBARC = 0;
			foreach((array)$vet_COOP_CARACT_EMBARC as $vet_COOP_CARACT_EMBARCkey){
				$FISH_CPCEMB_TIPO = $_POST['FISH_CPCEMB_TIPO'][$cont_COOP_CARACT_EMBARC];
				$FISH_CPCEMB_PROPRIA = $_POST['FISH_CPCEMB_PROPRIA'][$cont_COOP_CARACT_EMBARC];
				$FISH_CPCEMB_MATERIAL = $_POST['FISH_CPCEMB_MATERIAL'][$cont_COOP_CARACT_EMBARC];
				$FISH_CPCEMB_TAMANHO = moeda($_POST['FISH_CPCEMB_TAMANHO'][$cont_COOP_CARACT_EMBARC]);
				$FISH_CPCEMB_CONSERV = $_POST['FISH_CPCEMB_CONSERV'][$cont_COOP_CARACT_EMBARC];
				if((!$FISH_CPCEMB_TIPO == 0) && (!$FISH_CPCEMB_PROPRIA == 0) && (!$FISH_CPCEMB_MATERIAL == 0) && (!$FISH_CPCEMB_CONSERV == 0)) {
					$sql_insert_COOP_CARACT_EMBARC = mysql_query("INSERT INTO TAB_FISH_COOCAR_EMBARC (FISH_COOCAR_ID, FISH_CPCEMB_TIPO, FISH_CPCEMB_PROPRIA, FISH_CPCEMB_MATERIAL, FISH_CPCEMB_TAMANHO, FISH_CPCEMB_CONSERV) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCEMB_TIPO', '$FISH_CPCEMB_PROPRIA', '$FISH_CPCEMB_MATERIAL', '$FISH_CPCEMB_TAMANHO', '$FISH_CPCEMB_CONSERV');", $db) or die(mysql_error());
				}
				$cont_COOP_CARACT_EMBARC++;
			}

			$vet_COOP_CARACT_MOTOR = $_POST['FISH_CPCMTR_TIPO'];
			$cont_COOP_CARACT_MOTOR = 0;
			foreach((array)$vet_COOP_CARACT_MOTOR as $vet_COOP_CARACT_MOTORkey){
				$FISH_CPCMTR_TIPO = $_POST['FISH_CPCMTR_TIPO'][$cont_COOP_CARACT_MOTOR];
				$FISH_CPCMTR_PROPRIO = $_POST['FISH_CPCMTR_PROPRIO'][$cont_COOP_CARACT_MOTOR];
				$FISH_CPCMTR_POTENCIA = moeda($_POST['FISH_CPCMTR_POTENCIA'][$cont_COOP_CARACT_MOTOR]);
				$FISH_CPCMTR_CONSERV = $_POST['FISH_CPCMTR_CONSERV'][$cont_COOP_CARACT_MOTOR];
				if((!$FISH_CPCMTR_TIPO == 0) && (!$FISH_CPCMTR_PROPRIO == 0) && (!$FISH_CPCMTR_CONSERV == 0)) {
					$sql_insert_COOP_CARACT_EMBARC = mysql_query("INSERT INTO TAB_FISH_COOCAR_MOTORES (FISH_COOCAR_ID, FISH_CPCMTR_TIPO, FISH_CPCMTR_PROPRIO, FISH_CPCMTR_POTENCIA, FISH_CPCMTR_CONSERV) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCMTR_TIPO', '$FISH_CPCMTR_PROPRIO', '$FISH_CPCMTR_POTENCIA', '$FISH_CPCMTR_CONSERV');", $db) or die(mysql_error());
				}
				$cont_COOP_CARACT_MOTOR++;
			}

			$vet_COOP_CARACT_TRALHAS = $_POST['FISH_CPCTRA_TRALHA'];
			$cont_COOP_CARACT_TRALHAS = 0;
			foreach((array)$vet_COOP_CARACT_TRALHAS as $vet_COOP_CARACT_TRALHASkey){
				$FISH_CPCTRA_TRALHA = $_POST['FISH_CPCTRA_TRALHA'][$cont_COOP_CARACT_TRALHAS];
				$FISH_CPCTRA_DESCRICAO = mb_convert_case($_POST['FISH_CPCTRA_DESCRICAO'][$cont_COOP_CARACT_TRALHAS], MB_CASE_UPPER, 'UTF-8');
				$FISH_CPCTRA_QTDE = $_POST['FISH_CPCTRA_QTDE'][$cont_COOP_CARACT_TRALHAS];
				if(!$FISH_CPCTRA_TRALHA == 0){
					$sql_insert_COOP_CARACT_TRALHAS = mysql_query("INSERT INTO TAB_FISH_COOCAR_TRALHAS (FISH_COOCAR_ID, FISH_CPCTRA_TRALHA, FISH_CPCTRA_DESCRICAO, FISH_CPCTRA_QTDE) VALUES ('$FISH_COOCAR_ID', '$FISH_CPCTRA_TRALHA', '$FISH_CPCTRA_DESCRICAO', '$FISH_CPCTRA_QTDE')", $db) or die(mysql_error());
				}
				$cont_COOP_CARACT_TRALHAS++;
			}
			
		/*
			echo"<script language=\"JavaScript\">
				alert('Inserido com sucesso!');
				</script>";
		*/				
			echo"<script language=\"JavaScript\">
				location.href=\"alterar_fish_familias.php?id_familia=$id_familia\";
				</script>";
		}
	}
?>
<?php require_once("includes/header-recebe.php");?>