<?php 
	error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
	include"../includes/conecta.php";
	$projeto = 7;
	session_start();
	if(!isset($_SESSION['user']) || !isset($_SESSION['login']) || !isset($_SESSION['senha']) || !isset($_SESSION['nome']) || !isset($_SESSION['nivel'])) {
		echo "Esta área é restrita. Clique ";
		echo "<a href=\"../index.html\">aqui</a>";
		echo " para fazer o LOGIN.";
		exit;
	} else {
		$sql_permissao = mysql_query("select * from TAB_MAIN_USERS_PROJECTS where ID_PROJETO = '$projeto' and ID_USER = '$_SESSION[user]'", $db);
		$num_busca = mysql_num_rows($sql_permissao);
		if ($num_busca == 0) {
			echo "Esta área é restrita. Clique ";
			echo "<a href=\"../index.html\">aqui</a>";
			echo " para fazer o LOGIN.";
			exit;
		} else {
			function reverse_date( $date ){
				return ( strstr( $date, '-' ) ) ? implode( '/', array_reverse( explode( '-', $date ) ) ) : implode( '-', array_reverse( explode(                '/', $date ) )      );
			}
			function moeda($get_valor) { 
                $source = array('.', ',');  
                $replace = array('', '.'); 
                $valor = str_replace($source, $replace, $get_valor);
                return $valor;
			}
			
			$id_camp = $_GET['id_camp'];
			$id_familia = $_GET['id_familia'];

			$FISH_AE_CAMPANHA = $_POST['FISH_AE_CAMPANHA'];
			$FISH_AE_TECNICO = $_POST['FISH_AE_TECNICO'];
			$FISH_AE_DT_ENTR_ATUAL = reverse_date($_POST['FISH_AE_DT_ENTR_ATUAL']);
			$FISH_AE_DT_ENTR_ANTERIOR = reverse_date($_POST['FISH_AE_DT_ENTR_ANTERIOR']);
			$FISH_AE_QT_ENTR_INTERVDIAS = $_POST['FISH_AE_QT_ENTR_INTERVDIAS'];
			$FISH_AE_BOO_PESCA_REALIZOU = $_POST['FISH_AE_BOO_PESCA_REALIZOU'];
			$FISH_AE_QT_PESCA_QTDEPESCARIAS = $_POST['FISH_AE_QT_PESCA_QTDEPESCARIAS'];
			$FISH_AE_QT_PESCA_MEDIADIASPESCARIAS = $_POST['FISH_AE_QT_PESCA_MEDIADIASPESCARIAS'];
			$FISH_AE_QT_PESCA_TOTALDIASPESCARIAS = $_POST['FISH_AE_QT_PESCA_TOTALDIASPESCARIAS'];
			$FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA = $_POST['FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA'];
			$FISH_AE_BOO_PESCA_USOUEQUIPS = $_POST['FISH_AE_BOO_PESCA_USOUEQUIPS'];
			$FISH_AE_FK_PESCA_NUSOUEQUIPS = $_POST['FISH_AE_FK_PESCA_NUSOUEQUIPS'];
			$FISH_AE_BOO_PESCA_LOCALMUDOU = $_POST['FISH_AE_BOO_PESCA_LOCALMUDOU'];
			$FISH_AE_BOO_PESCA_LOCALMELHOR = $_POST['FISH_AE_BOO_PESCA_LOCALMELHOR'];
			$FISH_AE_BOO_PESCA_RESULTMELHOR = $_POST['FISH_AE_BOO_PESCA_RESULTMELHOR'];
			$FISH_AE_BOO_PESCA_ESPECIESMUDOU = $_POST['FISH_AE_BOO_PESCA_ESPECIESMUDOU'];
			$FISH_AE_BOO_PESCA_CONDVIDAMELHOR = $_POST['FISH_AE_BOO_PESCA_CONDVIDAMELHOR'];
			$FISH_AE_QT_PESCA_MEDIAKQPESCARIA = moeda($_POST['FISH_AE_QT_PESCA_MEDIAKQPESCARIA']);
			$FISH_AE_BOO_PESCA_PRODVENDIDA = $_POST['FISH_AE_BOO_PESCA_PRODVENDIDA'];
			$FISH_AE_QT_PESCA_MEDIAKQVENDIDO = moeda($_POST['FISH_AE_QT_PESCA_MEDIAKQVENDIDO']);
			$FISH_AE_VL_PESCA_VALORKQVENDIDO = moeda($_POST['FISH_AE_VL_PESCA_VALORKQVENDIDO']);
			$FISH_AE_QT_PESCA_MEDIAKQCONSUMO = moeda($_POST['FISH_AE_QT_PESCA_MEDIAKQCONSUMO']);
			$FISH_AE_FK_PESCA_NENHUMAPESCARIA = $_POST['FISH_AE_FK_PESCA_NENHUMAPESCARIA'];
			$FISH_AE_BOO_PESCA_SATISFACAO = $_POST['FISH_AE_BOO_PESCA_SATISFACAO'];
			$FISH_AE_TXT_PESCA_SATISFACAO = mb_convert_case($_POST['FISH_AE_TXT_PESCA_SATISFACAO'], MB_CASE_UPPER, 'UTF-8');
			$FISH_AE_BOO_ATEND_SATISFACAO = $_POST['FISH_AE_BOO_ATEND_SATISFACAO'];
			$FISH_AE_TXT_ATEND_SATISFACAO = mb_convert_case($_POST['FISH_AE_TXT_ATEND_SATISFACAO'], MB_CASE_UPPER, 'UTF-8');
			$FISH_AE_BOO_COOP_FILIACAO = $_POST['FISH_AE_BOO_COOP_FILIACAO'];
			$FISH_AE_TXT_COOP_FILIACAO = mb_convert_case($_POST['FISH_AE_TXT_COOP_FILIACAO'], MB_CASE_UPPER, 'UTF-8');
			$FISH_AE_BOO_PESCA_FICHASOK = $_POST['FISH_AE_BOO_PESCA_FICHASOK'];
			$FISH_AE_FK_PESCA_FICHASMOTIVO = $_POST['FISH_AE_FK_PESCA_FICHASMOTIVO'];
			
			$comandosql = "UPDATE TAB_FISH_ACOMP_ENTREVISTA SET FISH_AE_CAMPANHA = '$FISH_AE_CAMPANHA', FISH_AE_TECNICO = '$FISH_AE_TECNICO', FISH_AE_DT_ENTR_ATUAL = '$FISH_AE_DT_ENTR_ATUAL', FISH_AE_DT_ENTR_ANTERIOR = '$FISH_AE_DT_ENTR_ANTERIOR', FISH_AE_QT_ENTR_INTERVDIAS = '$FISH_AE_QT_ENTR_INTERVDIAS', FISH_AE_BOO_PESCA_REALIZOU = '$FISH_AE_BOO_PESCA_REALIZOU', FISH_AE_QT_PESCA_QTDEPESCARIAS = '$FISH_AE_QT_PESCA_QTDEPESCARIAS', FISH_AE_QT_PESCA_MEDIADIASPESCARIAS = '$FISH_AE_QT_PESCA_MEDIADIASPESCARIAS', FISH_AE_QT_PESCA_TOTALDIASPESCARIAS = '$FISH_AE_QT_PESCA_TOTALDIASPESCARIAS', FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA = '$FISH_AE_QT_PESCA_MEDIAPESSOASPESCARIA', FISH_AE_BOO_PESCA_USOUEQUIPS = '$FISH_AE_BOO_PESCA_USOUEQUIPS', FISH_AE_FK_PESCA_NUSOUEQUIPS = '$FISH_AE_FK_PESCA_NUSOUEQUIPS', FISH_AE_BOO_PESCA_LOCALMUDOU = '$FISH_AE_BOO_PESCA_LOCALMUDOU', FISH_AE_BOO_PESCA_LOCALMELHOR = '$FISH_AE_BOO_PESCA_LOCALMELHOR', FISH_AE_BOO_PESCA_RESULTMELHOR = '$FISH_AE_BOO_PESCA_RESULTMELHOR', FISH_AE_BOO_PESCA_ESPECIESMUDOU = '$FISH_AE_BOO_PESCA_ESPECIESMUDOU', FISH_AE_BOO_PESCA_CONDVIDAMELHOR = '$FISH_AE_BOO_PESCA_CONDVIDAMELHOR', FISH_AE_QT_PESCA_MEDIAKQPESCARIA = '$FISH_AE_QT_PESCA_MEDIAKQPESCARIA', FISH_AE_BOO_PESCA_PRODVENDIDA = '$FISH_AE_BOO_PESCA_PRODVENDIDA', FISH_AE_QT_PESCA_MEDIAKQVENDIDO = '$FISH_AE_QT_PESCA_MEDIAKQVENDIDO', FISH_AE_VL_PESCA_VALORKQVENDIDO = '$FISH_AE_VL_PESCA_VALORKQVENDIDO', FISH_AE_QT_PESCA_MEDIAKQCONSUMO = '$FISH_AE_QT_PESCA_MEDIAKQCONSUMO', FISH_AE_FK_PESCA_NENHUMAPESCARIA = '$FISH_AE_FK_PESCA_NENHUMAPESCARIA', FISH_AE_BOO_PESCA_SATISFACAO = '$FISH_AE_BOO_PESCA_SATISFACAO', FISH_AE_TXT_PESCA_SATISFACAO = '$FISH_AE_TXT_PESCA_SATISFACAO', FISH_AE_BOO_ATEND_SATISFACAO = '$FISH_AE_BOO_ATEND_SATISFACAO', FISH_AE_TXT_ATEND_SATISFACAO = '$FISH_AE_TXT_ATEND_SATISFACAO', FISH_AE_BOO_COOP_FILIACAO = '$FISH_AE_BOO_COOP_FILIACAO', FISH_AE_TXT_COOP_FILIACAO = '$FISH_AE_TXT_COOP_FILIACAO', FISH_AE_BOO_PESCA_FICHASOK = '$FISH_AE_BOO_PESCA_FICHASOK', FISH_AE_FK_PESCA_FICHASMOTIVO = '$FISH_AE_FK_PESCA_FICHASMOTIVO' WHERE FISH_AE_ID = '$id_camp';";

			$sql = mysql_query($comandosql, $db);			
		/*
			echo"<script language=\"JavaScript\">
				alert('Inserido com sucesso!');
				</script>";
		*/				
			echo"<script language=\"JavaScript\">
				location.href=\"cadastrar_fish_dados_campanha.php?id_camp=$id_camp&id_familia=$id_familia\";
				</script>";
		}
	}
?>
<?php require_once("includes/header-recebe.php");?>